### ISSUE TITLE
In a room any message is a reply

### ISSUE THREAD

**Issue by danteissaias** [tulir/gomuks#102]
All messages in a room contain an empty reply.

```
"m.relates_to": {
      "m.in_reply_to": {}
    },
```

This causes rendering bugs in some bridges such as discord.

**Comment by tulir** [comment]
I'll probably fix this at some point just to make the event json cleaner, but it's perfectly valid now too.

The bug is in the discord bridge.

**Comment by danteissaias** [comment]
Okay cool.

**Comment by danteissaias** [comment]
This is a much more severe issue now, since the new Riot.im android client marks messages sent by gomuks as malformed.

**Comment by tulir** [comment]
vector-im/riotX-android#447

**Comment by danteissaias** [comment]
Thanks for clearing that up
