### ISSUE TITLE
First login SIGSEGV

### ISSUE THREAD

**Issue by trmendes** [tulir/gomuks#104]
I'm getting this SIGSEGV when I try to login into matrix.org using gomuks for the first time.

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x564fd25a9268]

goroutine 25 [running]:
maunium.net/go/gomuks/debug.Recover()
	debug/debug.go:109 +0x96
panic(0x564fd2bb32e0, 0x564fd307fb80)
	/usr/lib/go/src/runtime/panic.go:679 +0x1b6
maunium.net/go/gomuks/matrix.(*HistoryManager).store(0x0, 0xc000093d40, 0xc004e3d890, 0x1, 0x1, 0x564fd25ae701, 0x0, 0x0, 0x0, 0x0, ...)
	matrix/history.go:152 +0x58
maunium.net/go/gomuks/matrix.(*HistoryManager).Append(...)
	matrix/history.go:144
maunium.net/go/gomuks/matrix.(*Container).HandleMessage(0xc00006a960, 0x22, 0xc002b18900)
	matrix/matrix.go:381 +0x1d3
maunium.net/go/gomuks/matrix.(*Container).HandleMembership(0xc00006a960, 0x22, 0xc002b18900)
	matrix/matrix.go:441 +0x9d
maunium.net/go/gomuks/matrix.(*GomuksSyncer).notifyListeners(0xc000a27b90, 0x22, 0xc002b18900)
	matrix/sync.go:188 +0x106
maunium.net/go/gomuks/matrix.(*GomuksSyncer).processSyncEvent(0xc000a27b90, 0xc000093d40, 0xc002b18900, 0x22)
	matrix/sync.go:162 +0x85
maunium.net/go/gomuks/matrix.(*GomuksSyncer).processSyncEvents(0xc000a27b90, 0xc000093d40, 0xc000414e00, 0x32, 0x3f, 0x22)
	matrix/sync.go:151 +0x58
maunium.net/go/gomuks/matrix.(*GomuksSyncer).ProcessResponse(0xc000a27b90, 0xc0004c4780, 0x0, 0x0, 0x4f, 0x1)
	matrix/sync.go:116 +0x2a6
maunium.net/go/mautrix.(*Client).Sync(0xc0001d8000, 0xc00024e000, 0x0)
	/home/thiago/go/pkg/mod/maunium.net/go/mautrix@v0.1.0-alpha.3.0.20190622085722-6406f15cb8e3/client.go:225 +0x280
maunium.net/go/gomuks/matrix.(*Container).Start(0xc00006a960)
	matrix/matrix.go:272 +0x10c
created by maunium.net/go/gomuks/matrix.(*Container).Login
	matrix/matrix.go:150 +0x1e0

**Comment by ReK2Fernandez** [comment]
I get same issue

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55abe602c228]

goroutine 11 [running]:
maunium.net/go/gomuks/debug.Recover()
	debug/debug.go:109 +0x96
panic(0x55abe6635640, 0x55abe6b01b80)
	/usr/lib/go/src/runtime/panic.go:679 +0x1b6
maunium.net/go/gomuks/matrix.(*HistoryManager).store(0x0, 0xc001c2bba0, 0xc002d698c0, 0x1, 0x1, 0xf8138701, 0x0, 0x0, 0x0, 0x0, ...)
	matrix/history.go:152 +0x58
maunium.net/go/gomuks/matrix.(*HistoryManager).Append(...)
	matrix/history.go:144
maunium.net/go/gomuks/matrix.(*Container).HandleMessage(0xc0004e8e40, 0x22, 0xc00074f200)
	matrix/matrix.go:381 +0x1d3
maunium.net/go/gomuks/matrix.(*GomuksSyncer).notifyListeners(0xc0003ec5a0, 0x22, 0xc00074f200)
	matrix/sync.go:188 +0x106
maunium.net/go/gomuks/matrix.(*GomuksSyncer).processSyncEvent(0xc0003ec5a0, 0xc001c2bba0, 0xc00074f200, 0x22)
	matrix/sync.go:162 +0x85
maunium.net/go/gomuks/matrix.(*GomuksSyncer).processSyncEvents(0xc0003ec5a0, 0xc001c2bba0, 0xc0004b2200, 0x32, 0x3f, 0x22)
	matrix/sync.go:151 +0x58
maunium.net/go/gomuks/matrix.(*GomuksSyncer).ProcessResponse(0xc0003ec5a0, 0xc000098c60, 0x0, 0x0, 0x38, 0x1)
	matrix/sync.go:116 +0x2a6
maunium.net/go/mautrix.(*Client).Sync(0xc0004ea000, 0xc000174150, 0x0)
	/home/rek2/go/pkg/mod/maunium.net/go/mautrix@v0.1.0-alpha.3.0.20190622085722-6406f15cb8e3/client.go:225 +0x280
maunium.net/go/gomuks/matrix.(*Container).Start(0xc0004e8e40)
	matrix/matrix.go:272 +0x10c
created by maunium.net/go/gomuks/matrix.(*Container).Login
	matrix/matrix.go:150 +0x1e0
```
I am using:
- wayland
- sway
- matrix.hispagatos.org homeserver

**Comment by tulir** [comment]
This should be fixed by one of the recent commits
