### ISSUE TITLE
Name/Time layout in Chatfeed

### ISSUE THREAD

**Issue by ohyran** [tulir/gomuks#106]
The text feed is currently cramping the text if the window is smaller than full screen since the timestamp and sender name are kept in a different column.

I would like to suggest putting timestamp and text in the same column, ensure different font color and perhaps [HH:MM] layout for time, to create a block quote that way text isn't squished together and is still as readable and scannable as the current layout.

**Comment by ohyran** [comment]
.... and I'm an idiot... So for those who find this you can set it sort of by typing in /toggle baremessages or /toggle users to hide the username list or make the messages simple (sadly no images but slimmer name+post setup).

Not closing since it would be cool to have a combo of baremessages with nice images too. But dev may close since this is now kinda fringe. <3

**Comment by tulir** [comment]
You can still click to open images in your default image viewer. Probably not going to add the pixel rendering to bare messages mode at least any time soon.
