### ISSUE TITLE
Show encrypted images with pantalaimon 0.5

### ISSUE THREAD

**Issue by Midek** [tulir/gomuks#110]
Pantalaimon 0.5 just came out, and it now supports decrypting media.
Unfortunately gomuks will still fail with 'Failed to display image' message.

When accessing the mxc of the media manually, pantalaimon did manage to decrypt it properly so i think gomuks should be able to access it as well.

**Comment by tulir** [comment]
This was found to be an issue in pantalaimon: matrix-org/pantalaimon#43
