### ISSUE TITLE
Allow toggle of joins/leaves

### ISSUE THREAD

**Issue by afranke** [tulir/gomuks#123]
I know in Matrix people tend to stay in rooms forever, but rooms that are bridged to IRC still have a lot of these events and they can make it *very* difficult to read a conversation.

**Comment by donpdonp** [comment]
another spin on this feature is to display part/join in the room, but to not flag the room as unread due to new part/join msgs.

**Comment by sicelo** [comment]
I also vote for a toggle, i.e. a way for gomuks to not show any joins/parts.

> another spin on this feature is to display part/join in the room, but to not flag the room as unread due to new part/join msgs.

Although somehow related, this is a different feature and I think it belongs to a different issue (there is now #278 ). The original request means not having them at all in the chat 'window'

**Comment by vinniec** [comment]
+1
can be useful to have more clean message list
