### ISSUE TITLE
Sensitive configuration in a separate file

### ISSUE THREAD

**Issue by MRAAGH** [tulir/gomuks#125]
Currently, the matrix access token is in the main configuration file, together with everything else.
Once we start getting more configuration options, we'll start sharing and syncing configuration files (for example in a public repository). Having the access token in the same file is a bad idea because you could accidentally leak it!

**Comment by tulir** [comment]
I don't think there will be any more config options. Preferences are already in a separate file (`~/.cache/gomuks/preferences.yaml`) and are stored in Matrix account data. `notify_sound` should probably be moved there too.

**Comment by MRAAGH** [comment]
Sorry, I did not realize there was another file for preferences! I'm guessing that is also where the custom keybindings would go?

**Comment by MRAAGH** [comment]
Closing this for redundancy
