### ISSUE TITLE
vi (vim) mode

### ISSUE THREAD

**Issue by MRAAGH** [tulir/gomuks#129]
Vim users get annoyed when we need to type without Vim keybindings. I realize this is a lot to ask, because the editor would need to be turned into a modal editor, and sequenced key bindings would need to be implemented. I might try to make it myself, as a plugin or fork.

Currently, gomuks is particularly unfriendly to Vim users, because whenever you try to go to normal mode (by pressing escape), your message is deleted!

**Comment by sir-marv** [comment]
Would love to be able to navigate using vim bindings as well, or the ability to create custom key bindings.

**Comment by binex-dsk** [comment]
absolutely, not having a vi mode just makes it 10x harder for me to use

for example, I was thinking something like this:
- `:r<number>` or `:room<number>` would put you in the room that is <number> down from the top
- `:d<number>` or `:dm<number>` would put you in the direct message that is <number> down from the top

and of course, regular vi stuff like the arrow keys, replace/delete operations, etc.

**Comment by cre-eledia** [comment]
Would love that too. Custom key bindings might be even better.

**Comment by pataquets** [comment]
Cross-linking to related issue #112.
