### ISSUE TITLE
More information in the bottom bar: room name, unread rooms

### ISSUE THREAD

**Issue by MRAAGH** [tulir/gomuks#131]
I noticed there is already an option to hide the room list. This is a good option to have, since the room list takes a lot of screen space and presents little useful information. However, there are a few pieces of information that I feel are missing once the room list is hidden:
- the name of the current room
- the number of rooms with unread messages (or a list of their names)

I think this information would nicely fit in the bar above the input box. More noticeable and better contained compared to being scattered around the room list. Less shiny, but a lot more efficient ;)

**Comment by ReK2Fernandez** [comment]
will be nice to be able to add the output of a command... that way people can add the output of anything, to for example ping output to calculate lag..

**Comment by MRAAGH** [comment]
@ReK2Fernandez ooh, you mean the way it's customizable in Weechat? That would be cool too, then everyone would be able to make the bar whatever they want. I'd kinda like to have a clock, for example. Along with room name and notification list.

But with more customizability, the program becomes more complicated and buggy and harder to maintain, I'm not sure if gomuks is really at that stage yet, since there are a lot of other more important missing features. As always, it comes down to the owner to decide. What do you think, @tulir? Customizable statusbar some day?
