### ISSUE TITLE
Part of room history fails to load

### ISSUE THREAD

**Issue by MRAAGH** [tulir/gomuks#136]
Sometimes when you switch to a room, it doesn't load all the way to the present. After this happens, no amount of room switching fixes it, it is only fixed by quitting and reloading gomuks.

I haven't found a way to reproduce this issue, but it is not rare and it is rather annoying. It's happened to me in all the rooms I use often. Happens without pantalaimon too.

Waiting for someone to find a reliable way to reproduce this!

**Comment by ReK2Fernandez** [comment]
I experienced this as well.
