### ISSUE TITLE
plaintext mode: returning to normal mode hangs if text was inputted

### ISSUE THREAD

**Issue by pltrz** [tulir/gomuks#138]
If you go into plaintext mode, and enter any text while in plaintext mode before pressing `enter` to return to normal mode, the program will hang.

0. open gomuks
0. press `[ctrl]-[L]` to enter plaintext mode
0. enter any text
0. press `[enter]` to return to normal mode
0. program hangs

**Comment by MRAAGH** [comment]
Only happens when entering with ctrl+L, not alt+L (maybe that's why we didn't find it earlier)
