### ISSUE TITLE
Can't re build gomuks

### ISSUE THREAD

**Issue by krinklefingers** [tulir/gomuks#144]
So my computer shut down with out properly shutting down gomuks and when I rebooted it I was unable to start gomuks again. I tried clearing the cache and that didn't work.
Then I tried reinstalling go muks and when I try and build gomuks.go I am met with this error:

gomuks.go:25:2: cannot find package "maunium.net/go/gomuks/config" in any of:
	/usr/lib/go-1.10/src/maunium.net/go/gomuks/config (from $GOROOT)
	/home/USER/go/src/maunium.net/go/gomuks/config (from $GOPATH)
gomuks.go:26:2: cannot find package "maunium.net/go/gomuks/debug" in any of:
	/usr/lib/go-1.10/src/maunium.net/go/gomuks/debug (from $GOROOT)
	/home/USER/go/src/maunium.net/go/gomuks/debug (from $GOPATH)
gomuks.go:27:2: cannot find package "maunium.net/go/gomuks/interface" in any of:
	/usr/lib/go-1.10/src/maunium.net/go/gomuks/interface (from $GOROOT)
	/home/USER/go/src/maunium.net/go/gomuks/interface (from $GOPATH)
gomuks.go:28:2: cannot find package "maunium.net/go/gomuks/matrix" in any of:
	/usr/lib/go-1.10/src/maunium.net/go/gomuks/matrix (from $GOROOT)
	/home/USER/go/src/maunium.net/go/gomuks/matrix (from $GOPATH)
main.go:30:2: cannot find package "maunium.net/go/gomuks/ui" in any of:
	/usr/lib/go-1.10/src/maunium.net/go/gomuks/ui (from $GOROOT)
	/home/USER/go/src/maunium.net/go/gomuks/ui (from $GOPATH)

Now I can't even re-compile it. What do?

**Comment by tulir** [comment]
That Go version looks too old

**Comment by krinklefingers** [comment]
Hmm? I pulled it off the package library. That could explain it. Where do you get yours from?
I also followed the instructions you give, but, that doesn't give me the actual go repo is what my friend told me.

**Comment by pltrz** [comment]
@krinklefingers what OS are you using? If it's linux, what distro?

**Comment by pltrz** [comment]
also: what steps did you take to install Go?

**Comment by krinklefingers** [comment]
> @krinklefingers what OS are you using? If it's linux, what distro?

I am using Linux Mint.
I followed the instructions verbatim off the website.

**Comment by pltrz** [comment]
What version of Go do you have? I think you need >= 1.12

**Comment by krinklefingers** [comment]
I have what's on the webiste; 1.14.12 I think

**Comment by pltrz** [comment]
alright, the version is probably fine then. you can double check with `go version`

then, try force deleting the cache [0]

```
$ sudo rm -r $HOME/go
```

then, make sure you're on the latest master and try rebuilding

```
$ cd gomuks
$ git pull --rebase
$ go build
```

------------------------------------------------

[0] there's a way to not bruteforce this, I just don't know it and don't really care

**Comment by krinklefingers** [comment]
Ok, that's weird cause I installed off the link, but, it say I have 1.10.4??? What's with that?
Thank you for your help, btw

**Comment by krinklefingers** [comment]
Ok, so, I found the out of date package and ran the installer. It succesfully installed, but, now it is giving me then when I attempt to run ./gomuks:

panic: yaml: control characters are not allowed [recovered]
	panic: yaml: control characters are not allowed

goroutine 1 [running]:
maunium.net/go/gomuks/debug.Recover()
	/home/dillon/Desktop/gomuks/debug/debug.go:109 +0x94
panic(0xaaaea0, 0xc000480020)
	/snap/go/5646/src/runtime/panic.go:969 +0x166
maunium.net/go/gomuks/config.(*Config).load(0xc0002a99e0, 0xb5c9d2, 0x6, 0xc00002b1a0, 0x1b, 0xb77c9a, 0xb, 0xb30cc0, 0xc0002a99e0)
	/home/dillon/Desktop/gomuks/config/config.go:212 +0x553
maunium.net/go/gomuks/config.(*Config).Load(0xc0002a99e0)
	/home/dillon/Desktop/gomuks/config/config.go:140 +0x7c
maunium.net/go/gomuks/config.(*Config).LoadAll(0xc0002a99e0)
	/home/dillon/Desktop/gomuks/config/config.go:127 +0x40
main.NewGomuks(0xc08f88, 0xc00002b1a0, 0x1b, 0xc00002b1e0, 0x1a, 0xc00002b200, 0x16, 0x0)
	/home/dillon/Desktop/gomuks/gomuks.go:50 +0x155
main.main()
	/home/dillon/Desktop/gomuks/main.go:68 +0x396

**Comment by pltrz** [comment]
try removing your config and cache. the default locations  for them are at `~/.config/gomuks` and `~/.cache/gomuks`

**Comment by krinklefingers** [comment]
Sorry for the late reply: Yep that did the trick! Thank you!
