### ISSUE TITLE
Activate `hide_user_list`

### ISSUE THREAD

**Issue by aparcar** [tulir/gomuks#145]
Hi, can somebody please advise me on how to activate `hide_user_list`? Should it go to a sub dict in the config.yaml?

**Comment by pltrz** [comment]
try `/toggle users`

**Comment by aparcar** [comment]
Thanks that works!

**Comment by pltrz** [comment]
> Thanks that works!

no problem! don't forget to check out [the wiki](https://github.com/tulir/gomuks/wiki) for more info.
