### ISSUE TITLE
sent messages stuck as "Sending..."

### ISSUE THREAD

**Issue by Midek** [tulir/gomuks#151]
After sending new message even though its actually sent and other clients can see it, it stays greyed out as if it was not yet sent from gomuks.
Example (new version on the left):
https://tube.midov.pl/videos/watch/a26706b2-1359-4618-9a89-4a419bbac316

**Comment by julianuu** [comment]
I have this too. Except after 20 seconds or so its not greyed out anymore

**Comment by pahosler** [comment]
I've had this happen as well, but for me it became actual lag until eventually after 2 minutes the message didn't send. I was monitoring in the element client.

- repeatable: **unknown**


go version go1.14.2 linux/amd64 running in Windows 10 WSL 2

**gomuks_0.1.2-1_amd64.deb**

NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
VERSION_CODENAME=bionic
