### ISSUE TITLE
Use $XDG_DOWNLOAD_DIR for downloads

### ISSUE THREAD

**Issue by kennylevinsen** [tulir/gomuks#157]
Currently, ~/Downloads is always used, regardless of what `$XDG_DOWNLOAD_DIR` dictates is the correct location for downloads. See https://www.freedesktop.org/wiki/Software/xdg-user-dirs/ (or https://wiki.archlinux.org/index.php/XDG_user_directories).

$XDG_DOWNLOAD_DIR should be used first, and only if not set should `~/Downloads` be used.

**Comment by tulir** [comment]
Need to implement some way to read `user-dirs.dirs` first since `XDG_DOWNLOAD_DIR` isn't in the environment by default

**Comment by wvffle** [comment]
In my opinion it should be configurable in gomuks config. I'd even save to `$XDG_DOWNLOAD_DIR/gomuks` by default

**Comment by tulir** [comment]
It is configurable, this issue is about defaulting to `$XDG_DOWNLOAD_DIR` instead of `$HOME/Downloads`
