### ISSUE TITLE
html render wont create links

### ISSUE THREAD

**Issue by r3k2** [tulir/gomuks#163]
I already commented this to you on #gomuks but as a reminder since I see there is no update on this issue. when someone post a url, or specially when a RSS bot post a feed with html and a link, gomuks will render the tittle etc fine, but will not create it under a html link so we can click on it.
how to reproduce? 
just enter channel #cyberpunk:hispagatos.org that is public and check all the bot posts with gomuks you will not be able to click, or even see the html link to copy/paste into the browser...

**Comment by tulir** [comment]
Closing in favor of #168 since that's a bit more descriptive
