### ISSUE TITLE
Can't paste login details on login screen

### ISSUE THREAD

**Issue by codevenkat** [tulir/gomuks#164]
I use a password manager for my password but it seems that you can't paste the password in the login screen.

**Comment by mferstl** [comment]
If you use the mouse button for pasting, most interactive tools in the shell require the pressing of the "shift key" and pressing the mouse button.  Usually you can also use the combination of "Shift-Insert" to insert text from the copy-paste buffer to the shell. Bonus: It depends on your graphical window-manager :)

**Comment by codevenkat** [comment]
Shift+Ins does not seem to work

**Comment by tulir** [comment]
There's nothing preventing normal terminal pasting there, <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd> works fine for me.

Multi-line input fields like the message composer also support <kbd>Ctrl</kbd>+<kbd>V</kbd> to bypass the terminal (have gomuks read the clipboard directly instead), but I think I forgot to support for that in the single-line input field component.

**Comment by AdriDevelopsThings** [comment]
Will the issue be fixed? I can't use gomuks because my password is very long, and I don't want to type it in.

**Comment by G2G2G2G** [comment]
There is no issue here, gomuks doesn't override your terminal settings. Like 99% of terminals.. to copy and paste you need to add a shift in there e.g.:
shift+ctrl+c
shift+ctrl+v

**Comment by AdriDevelopsThings** [comment]
Thanks, but I know I have to use shift in the shortcut. But it doesn't work: Not with shift and not without shift.

**Comment by mcronce** [comment]
Having the same issue - tried running `gomuks` in `konsole`, `terminator`, and `alacritty`.  Not sure if it's length (126 characters) or some of the symbols or something like that; pasting into a plain old bash prompt does show the whole password, though.

**Comment by mcronce** [comment]
Just tried building it from `master` and it seems to work fine there, so must have been fixed sometime since 0.2.4 released
