### ISSUE TITLE
SSO hangs on "Synchronizing"

### ISSUE THREAD

**Issue by Idesmi** [tulir/gomuks#166]
This affects Single Sign-On method.
The webpage opens as expected, I log-in,
then the client starts synchronizing with no end.

To reproduce, proceed to SSO in the Mozilla Matrix Server.
I made sure the access token had been issued and was present in config.yaml
![image](https://user-images.githubusercontent.com/21034950/81690814-5bb0e880-944b-11ea-970f-ddffb1cfbebc.png)

**Comment by tulir** [comment]
It works fine for me. Can you check if there's anything weird in `/tmp/gomuks/debug.log`?

**Comment by Idesmi** [comment]
> anything weird in `/tmp/gomuks/debug.log`?
```
[2020-05-12 14:48:24] Sync failed: msg=Failed to GET JSON to /_matrix/client/r0/sync code=400 wrapped=M_INVALID_PARAM: No such filter
[2020-05-12 14:48:34] [Matrix] GET https://mozilla.modular.im/_matrix/client/r0/sync?filter=3&timeout=30000

```

**Comment by tulir** [comment]
Not sure how that would happen, but try clearing cache (`rm -rf ~/.cache/gomuks`) or at least removing the `filter_id` field in `auth-cache.yaml`

**Comment by Idesmi** [comment]
Clearing ~/.cache/gomuks alone worked.
Is there a way to seamlessly switch server? I am inclined to think this happened because I previously logged in a different non-SSO server.
