### ISSUE TITLE
Display (& open) inline links

### ISSUE THREAD

**Issue by n-peugnet** [tulir/gomuks#168]
When hypertext links are added with the markdown syntax `[text](link)` there is no way in gomuks to know that there is a hyperlink on `text`.

So there are 2 things:
1.  The hyperlink should be visible maybe by underlining `text`.
2.  It should be possible to open this link. This is more complicated. Maybe at first you could add the link under the message (a little bit like the URL previews on riot) and leave the open action to the terminal emulator.

**Comment by tulir** [comment]
Open inline links by clicking needs #91, but I guess just including the links in the message could come as a temporary solution first.

**Comment by r3k2** [comment]
@tulir Any news on this? if you point me in the right direction to where this is happening in the code I can try to fix it.

**Comment by SlidingHorn** [comment]
I'm not a dev, so I have no idea how this would be implemented, but one example that may be enlightening or inspiring is how `tut` handles opening/copying links in toots on Mastodon. Basically if there's a link within the post you're currently viewing, you hit `o` to show a list of links contained, and from there, you highlight the link you want and either hit `o` again to open it in a browser or `y` to copy the URL.

https://github.com/RasmusLindroth/tut

This may or may not be helpful at all, but I figured I'd drop the link just in case it sparks some inspiration for you =)

**Comment by rhaberkorn** [comment]
I still often have problems opening links. Even with Urxvt, it might not detect the entire URL. The only thing I can do in this case, is either entering plaintext mode or using `/copy` and manually extracting the URL. 
Why does `/open` not work on messages with URLs? That would work with `xdg-open`.

**Comment by tulir** [comment]
It requires a terminal with inline link support, urxvt probably doesn't support it

**Comment by rhaberkorn** [comment]
> It requires a terminal with inline link support, urxvt probably doesn't support it

Urxvt supports detecting and highlighting URLs in plain text. This fails if the URL is too long and split on 2 lines while a sidebar is enabled. That's why plain-text mode helps.

Are you talking about URLs being marked by special escape sequences? No Urxvt does not support that. But that's also not a standardized terminal capability (those are unfortunately stuck in the 80s). How do you decide which terminal supports it and which one doesn't?

**Comment by rhaberkorn** [comment]
Ah yeah, I see...
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#detecting-availability-of-the-feature
