### ISSUE TITLE
[feature-request] self defined alias cmds

### ISSUE THREAD

**Issue by cremesk** [tulir/gomuks#176]
Hello,

would it be possible to introduce self-defined aliases?

suggestion:
```
/alias <list|add|del>

/alias list
/alias add <name> <value>
/alias del <name>
```

Thanks a lot!

EDIT:
eg: `/alias add hello "Hey there! Welcome to #community, how are you?"`
to use `/hello`

**Comment by wvffle** [comment]
Just a reminder, that `/alias` command already exists
