### ISSUE TITLE
failed to open crypto store: gob: unknown type id or corrupted data

### ISSUE THREAD

**Issue by r3k2** [tulir/gomuks#179]
So it was working just fine, I restarted my PC and now I get that msg...
says corrupted so I go to .cache/gomuks and delete everything.
restart and start gomuks same msg... :(  @tulir 

![gomuks-issue](https://user-images.githubusercontent.com/5316229/84300059-11a64a00-ab52-11ea-8a0b-fd9047df31c3.png)

**Comment by navanchauhan** [comment]
Path for macOS users: `~/Library/Application Support/gomuks/crypto.gob`
