### ISSUE TITLE
Requesting the ability to ignore users.

### ISSUE THREAD

**Issue by ghost** [tulir/gomuks#183]
Thank you for this client - I love its simplicity and quality especially compared to the Riot.im client. However, I would like to be able to ignore users without leaving the client (I have ignored users with the Riot.im client in the past, and it's not a client I would say I love to use), preferably with the `/ignore` or `/unignore` commands if they have not been implemented already.

**Comment by mcepl** [comment]
Or time limited `/ignore [days]`? So, when the guy stops letting out nonsense in the current thread, he would automagically return?
