### ISSUE TITLE
Emojify reactions

### ISSUE THREAD

**Issue by n-peugnet** [tulir/gomuks#186]
I don't know how Matrix reactions really work, but I suppose that to send emoji reactions, we just have to put its unicode tag in the content of the reaction. As #65 has been merged, I guess we could reuse the `emoji.Sprint(text)` function for this task. I looked a little bit at the code and identified some functions where to put It, but I don't really know which one would be the best:

https://github.com/tulir/gomuks/blob/db108d4e6bfced55724bf9d82dc32de3ad7764a2/ui/commands.go#L194
https://github.com/tulir/gomuks/blob/db108d4e6bfced55724bf9d82dc32de3ad7764a2/ui/room-view.go#L680

I am not really used to go and I do not manage to make the app built from source work correctly alongside the packaged one, so I would prefer not to make the change myself.

**Comment by tulir** [comment]
You can already just autocomplete emojis, but if someone wants to make a PR that makes /react optionally (either the existing disable_emojis option or a new one) use `emoji.Sprint`, I'd probably accept it.

**Comment by n-peugnet** [comment]
I didn't know it was possible :laughing: ! I just tried to hit <kbd>tab</kbd> and it worked as expected. I will add it to the wiki.

**Comment by tulir** [comment]
This was added in #354
