### ISSUE TITLE
Got this working on OSX with a socks5 proxy

### ISSUE THREAD

**Issue by ChrisPritchard** [tulir/gomuks#188]
I got this running on OSX, connecting to our matrix server with e2ee. To do so I had to do a couple of things, so just noting them here (not really an issue per se, more an FYI):

- I needed to install libolm, view `brew install libolm`
- I needed to manually `go get github.com/russross/blackfriday` (the go get for gomuks complained about not finding blackfriday/v2)

After the above I could compile. However, our matrix server is accessed over a socks5 proxy, and so to get this working I had to:

- find the client connection, which is at https://github.com/tulir/gomuks/blob/master/matrix/matrix.go#L116
- added the following lines underneath the setting of deviceid etc:

```go
proxyURL, _ := url.Parse("socks5://our-proxy-url:port")
c.client.Client.Transport = &http.Transport{Proxy: http.ProxyURL(proxyURL)}
```

Worked like a charm :) Not sure there is another way to set a proxy in the tool?

gomuks is awesome, thanks :) Some people on our team I think will be happy to use it over the much more clunky element.im. We're all OSX unfortunately though, so I'm glad I was able to get it working.

**Comment by tulir** [comment]
> I needed to install libolm

That's mentioned in the [installation instructions](https://github.com/tulir/gomuks/wiki/Installation)

> the go get for gomuks complained about not finding blackfriday/v2

`go get` isn't used for installing programs nowadays, cloning the repo and `go build` or `go install` is the correct way (as the installation instructions show)

> Not sure there is another way to set a proxy in the tool?

Go's http library will use the `http_proxy` environment variable automatically

**Comment by ChrisPritchard** [comment]
Thanks for the clarification.
