### ISSUE TITLE
Empty rooms only in gomuks - /leave, /clearcache, and purge room API can't remove them

### ISSUE THREAD

**Issue by BurnyBoi** [tulir/gomuks#192]
I have many empty rooms that I am unable to remove. They show under the "People" tag. These only show in gomuks for me (also checked in Mirage, Element, and Fractal). I've run `/leave` on every room, then did a `/clearcache`, and am still seeing these here. After that didn't work, I tried running the purge room API in synapse to remove a few of them from the database, cleared cache and resynced, and did not see any rooms removed.

![pic-selected-200821-1929-00](https://user-images.githubusercontent.com/41203525/90942909-b01e1980-e3e5-11ea-8e10-ead60315dc51.png)

**Comment by apetresc** [comment]
@BurnyBoi Can you expand on how you removed them?

**Comment by aurelg** [comment]
You can use [Element](https://app.element.io). Join any room, and type `/devtools`. This opens a panel in which you can choose `Explore account data`, then `m.direct`. A JSON structure representing your direct messages will pop up. Scroll down, click `Edit`, and remove empty rooms. Then click `Send`. :heavy_check_mark: 
I wonder where these empty rooms come from, though. :thinking:

**Comment by Juliaria08** [comment]
Make a command to do that cloud be more easy

**Comment by asakura42** [comment]
@tulir Please, reopen an issue. I hope there is any solution to delete empty rooms without manual devtools fixing.

**Comment by tulir** [comment]
This is a duplicate of #162

**Comment by asakura42** [comment]
Oops. Thx.
