### ISSUE TITLE
olm/olm.h no directory found

### ISSUE THREAD

**Issue by krinklefingers** [tulir/gomuks#193]
Hi, I am running on a Gentoo machine and when I try and build this application I receive the following error: 

# maunium.net/go/mautrix/crypto/olm
/root/go/pkg/mod/maunium.net/go/mautrix@v0.7.0/crypto/olm/account.go:4:11: fatal error: olm/olm.h: No such file or directory
    4 | // #include <olm/olm.h>
      |           ^~~~~~~~~~~
compilation terminated.

I can't infer exactly what to do from this all I can tell is that there apparently is no olm/olm/h directory. Can anyone give me some information?

**Comment by krinklefingers** [comment]
> You need to install olm.

How do I do that? I can't seem to find a source for it and I can't find it in my repositories.

**Comment by justjosias** [comment]
@krinklefingers You may need to install olm from source: https://gitlab.matrix.org/matrix-org/olm

**Comment by krinklefingers** [comment]
Thanks for your help, I downloaded and installed olm and successfully built gomuks, but, now when I run ./gomuks It returns this error: ./gomuks: error while loading shared libraries: libolm.so.3: cannot open shared object file: No such file or directory 

I don't get it, I have recompiled olm several times all building the shared libraries.

**Comment by justjosias** [comment]
Is the path where you installed olm in `LD_LIBRARY_PATH`? 
Try: `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/path/to/olm"`

**Comment by krinklefingers** [comment]
All that command is doing is opening up a bash shell. I cloned the source code off github in my home directory and compiled it from there.

**Comment by tulir** [comment]
`ldd gomuks` should show what you're missing

**Comment by krinklefingers** [comment]
i'm missing lbolm.so.3

        linux-vdso.so.1 (0x00007ffe77d9c000)
        libolm.so.3 => not found
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/libstdc++.so.6 (0x00007f13d80e8000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f13d80c8000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f13d7f0d000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f13d7dca000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f13d8383000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/libgcc_s.so.1 (0x00007f13d7db0000)


?

**Comment by SethArchambault** [comment]
Got this olm issue too - maybe include this in the install docs?
