### ISSUE TITLE
Delete message by editing it to an empty message

### ISSUE THREAD

**Issue by wvffle** [tulir/gomuks#197]
One of the features I'm missing is deleting the contents of edited message to delete the whole message.

Right now, when someone tries to edit the message, deletes all content and presses `enter`, nothing happens. The input waits for the user to type something to edit the message to.

**Comment by justjosias** [comment]
This wouldn't delete the message anyway, since Matrix has an edit history. You're better off using redactions directly.

**Comment by wvffle** [comment]
Yup, just looked through the issues and found that I can do `/redact` and choose the message with keyboard.
I've updated the shortcuts wiki page with that info

**Comment by n-peugnet** [comment]
`/redact` is not a shortcut, it is a command. It was already documented in the _commands_ page of the wiki

**Comment by wvffle** [comment]
> `/redact` is not a shortcut, it is a command. It was already documented in the _commands_ page of the wiki

Yes, I know but what mattered for me is to be able to do it with *keyboard*, hence I put info how to do it in the shortcuts page of the wiki
