### ISSUE TITLE
Can't choose who to mention.

### ISSUE THREAD

**Issue by wvffle** [tulir/gomuks#198]
In one chat bridged by mautrix-telegram I have 2 users:
- `Jan Aaaa`
- `Jan Bbbb`

I want to mention the second one after typing `Jan<tab>` but I'm unable to select whom I want to mention.

**Comment by tulir** [comment]
This is the same as #199

**Comment by wvffle** [comment]
Well, what I meant by that is I can't do it in any way. Not by autocompletion, nor by mouse

**Comment by tulir** [comment]
I don't think the autocompletion options are supposed to work with a mouse, but you can click on the sender name in the message area to mention that user.

Clickable autocompletion options and cycling through options with tab can also be feature requests (in new issues)
