### ISSUE TITLE
Add an option to cycle through autocompletion entries using keyboard

### ISSUE THREAD

**Issue by wvffle** [tulir/gomuks#203]
As discussed in https://github.com/tulir/gomuks/issues/198#issuecomment-683479457

**Comment by n-peugnet** [comment]
Here is an example in Vim:
![Peek 2021-08-24 11-23](https://user-images.githubusercontent.com/23519418/130592308-8781b41c-3bd4-480b-b0f9-92874286355d.gif)

As in gomuks, autocompletions are triggered by <kbd>Tab</kbd> and showed in a row.

But additionally it highlights the first entry (which is in fact preselected) and allows to cycle between the propositions using <kbd>Tab</kbd> and <kbd>Shift</kbd> + <kbd>Tab</kbd>. If there are more propositions than the length of a row, these are paged and the page change automatically following the selected proposition.
