### ISSUE TITLE
Option to never collapse room lists

### ISSUE THREAD

**Issue by colemickens** [tulir/gomuks#208]
I can't really figure out how gomuks chooses what to show and what to collapse but I mostly don't want it ever hiding rooms from me. I looked around the wiki and didn't see any options for possibly configuring this.

Is this possible now, if not can you give me a few keywords to grep for in the source in hopes of me patching it?

Thanks!

**Comment by pataquets** [comment]
I would add it's quite annoying, since forces me to use the mouse to expand the collapsed channel list in order to Alt+Down to work. :thinking:
