### ISSUE TITLE
/edit allows to edit others messages

### ISSUE THREAD

**Issue by wvffle** [tulir/gomuks#217]
![Screenshot from 2020-09-04 18-33-38](https://user-images.githubusercontent.com/13330620/92263661-81676f00-eecc-11ea-95ea-0e8b32eda3e3.png)

As in the screenshot, `/edit` allows to select messages sent by other people and edit them. The change is only rendered in gomuks.

**Comment by wvffle** [comment]
@tulir why wontfix?

I guess that the easiest resolution to this problem would be to skip messages sent by others when selecting the message.

Having the ability to edit someone else's messages can be abused to check what the message was before it was redacted.
https://streamable.com/pbd69z

**Comment by tulir** [comment]
This is wontfix because there isn't really any need to prevent it. Message content not being removed when a message is redacted is a different bug (or possibly a feature)
