### ISSUE TITLE
Documentation Update: Notifications

### ISSUE THREAD

**Issue by russsharek** [tulir/gomuks#218]
Installing libnotify-bin on Debian and Mobian got notifications working.

In the case of Mobian, there was a notifications daemon running in phosh already. I had to add dunst to my i3wm setup on Debian.

Might be worth a mention in the FAQ. :)

**Comment by panmau** [comment]
Anything else that are needed to do to get notifications working?
I have dunst configured, use tilix as a dropdown terminal but don't get any notification popups. Maybe it thinks that I am still in the terminal somehow? Anyone has an idea what could be done here?
This is a crucial feature for the way I would like to use this client.
