### ISSUE TITLE
Error: "failed to initialize history: timeout"

### ISSUE THREAD

**Issue by thenktor** [tulir/gomuks#224]
Hi,

on Windows I cannot login anymore. After a crash I'm getting the error "failed to initialize history: timeout" when I try to login.

![](https://i.ibb.co/JKfhDjD/2020-09-08-08-32-49-gomuks-failed.png)

**Comment by thenktor** [comment]
Sorry, found the problem. Gomuks did not crash, just the window disappeared while gomuks was still running in background. Killed it using the task manager and now it works again.

Still the error message may be improved 😉

**Comment by diimdeep** [comment]
Same problem, same solution

**Comment by FoxySeta** [comment]
Same here. I also think the error message may be improved.
