### ISSUE TITLE
Cross compile to macOS

### ISSUE THREAD

**Issue by drasbeck** [tulir/gomuks#225]
This cool project doesn't have any ready made macOS binaries.

Crosss compiling go is usually pretty easy, here's a straightforward [guide](https://golangcookbook.com/chapters/running/cross-compiling/). I hope you'll include macOS in your build script.

**Comment by wvffle** [comment]
There's an open merge request on gitlab https://mau.dev/tulir/gomuks/-/merge_requests/1

**Comment by tulir** [comment]
I know how Go works :P

Cross-compiling isn't straightforward at all because encryption has C dependencies (libolm), I need to take serx's macOS docker image, update it and put it in https://mau.dev/tulir/gomuks-build-docker first. Might also look into making it build static binaries like the linux and windows ones do.

**Comment by drasbeck** [comment]
@wvffle good find.

@tulir, I never meant to imply that you didn't. =) I just saw the call for contributors in the wiki, and wanted to chip in. I never ran into much trouble cross compiling, but I also never made anything with C dependencies. And had I seen the open pull request, I would probably have kept my mouth shut. 😄 I hope you make good progress on this, when you have the time, as I would love to use Matrix in a more native TUI than Weechat-matrix.

**Comment by Amar1729** [comment]
I've written a simple homebrew tap for gomuks here: https://github.com/amar1729/homebrew-gomuks . Could be added to [the wiki](https://github.com/tulir/gomuks/wiki/Installation) if the author's comfortable with adding a user-provided Homebrew tap. 
When this gets more popular I'd like to add it to homebrew-core but I have a feeling they'd currently say it doesn't have enough github stars.

**Comment by tulir** [comment]
The CI has macOS builds now (both intel and apple silicon)
