### ISSUE TITLE
Support higher resolution image display in terminal emulators that support it

### ISSUE THREAD

**Issue by jezcope** [tulir/gomuks#228]
[Kitty](https://sw.kovidgoyal.net/kitty/) is a modern terminal emulator that implements its own [graphics protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol.html) for displaying images which is already [integrated with a number of tools](https://sw.kovidgoyal.net/kitty/integrations.html#scrollback-manipulation). [libsixel](https://github.com/saitoha/libsixel) also provides a way of displaying images in terminals supporting that protocol.

I was impressed to see gomuks already displays low-resolution versions of images in the terminal, but it would be cool to see one or both of the above implemented too.

**Comment by FoundOne** [comment]
I'd like to have sixel images support.

**Comment by jezcope** [comment]
Somehow I'd missed that this duplicates #103...
