### ISSUE TITLE
I've packed Gomuks for Gentoo

### ISSUE THREAD

**Issue by libre-hackerman** [tulir/gomuks#229]
Hi! I have written an Ebuid for Gomuks and stored the package _net-im/gomuks_ in my personal overlay, [elopez-r-overlay](https://gitlab.com/libre_hackerman/elopez-r-overlay) so is availabe to all the Gentoo users.

**Comment by tulir** [comment]
Feel free to add it to [the wiki](https://github.com/tulir/gomuks/wiki/Installation)
