### ISSUE TITLE
Unread status is sometimes not updated

### ISSUE THREAD

**Issue by wvffle** [tulir/gomuks#230]
When I read last messages in [#gomuks:maunium.net](https://matrix.to/#/#gomuks:maunium.net) and switched to another channel, the unread status has not updated. 

It happens from time to time, I have no idea when it finally decides to mark channel as read but restarts, scrolling the history nor sending a message helps that.

Here's the video: https://streamable.com/malldn

**Comment by lenormf** [comment]
For me it's after any new message is sent/received, I have to hit a key (any) for the UI to refresh.

**Comment by broukema** [comment]
This bug seems very similar to #285 where the use of `/clearcache` to solve this is given as a user-level hack.
