### ISSUE TITLE
Issues with light theme and failure to initialize crypto

### ISSUE THREAD

**Issue by Amolith** [tulir/gomuks#236]
I recently switched all of my devices to a light theme and there are text visibility issues with gomuks:
![image](https://user-images.githubusercontent.com/29460675/96009659-eb016400-0e0e-11eb-8073-cce7bc0920ac.png)

There's too little contrast between the foreground text and the background on the right and no contrast at all in room/PM list on the left; the only text that's visible is the umbrella emoji.

It also seems as I can't sign back in to take more screenshots or gather more info. After signing out, uninstalling `gomuks`, removing all the files, then installing `gomuks-git` to make sure I'm using the latest verison, I'm thrown this error when signing in:
![image](https://user-images.githubusercontent.com/29460675/96009926-39aefe00-0e0f-11eb-8ab1-f272ea4cc9ea.png)

They're likely unrelated issues and I can open a separate one for the second if necessary.

**Comment by ccao001** [comment]
I'm getting the same "failed to initialize crypto: ..." message.

**Comment by tulir** [comment]
Crypto issue: #246
Color issue: #23
