### ISSUE TITLE
Add option to disable image downloading

### ISSUE THREAD

**Issue by tulir** [tulir/gomuks#24]
Some people may not want the inline image rendering, so it should be possible to disable it.

**Comment by ison111** [comment]
Seconding this. I love the image rendering, however if I'm using it at work I not only don't want them rendered, but I'd also like to know that they aren't even downloaded.

It would also be great if there was a way to either open the image using an image viewer (this could possibly be set in the config) or to copy its URI into the clipboard.
For now when I've needed to see the original version of the image I've had to open up a second matrix client, view the image, and then close it.

**Comment by tulir** [comment]
`/uitoggle images` will now disable image rendering, I should probably add that autodownload disable option too though.

**Comment by tulir** [comment]
`/toggle downloads` has also existed for a while
