### ISSUE TITLE
Segmentation fault on login compleation

### ISSUE THREAD

**Issue by L0ric0** [tulir/gomuks#242]
on the completion of initial sync gomuks dies with a segfault. the stack trace is attached.

[error.txt](https://github.com/tulir/gomuks/files/5518083/error.txt)

Version: 0.2.1
go-version: 1.15.4

**Comment by tulir** [comment]
Go 1.15.3 is broken, don't use that

**Comment by L0ric0** [comment]
then go 1.15.4 also isn't working as  that was used to compile gomuks
