### ISSUE TITLE
Corrupted state after segmentation fault

### ISSUE THREAD

**Issue by Phenitei** [tulir/gomuks#243]
Hi,

Thank you for your awesome work !

After opening and using gomuks for a bit, I had to type `/quit` twice to get it to close, and the terminal showed me an error saying there'd been a null pointer dereference in a goroutine but that the program had recovered. I thought nothing of it, expecting errors in a client in developpment, and didn't save the exact crash logs.

Having tried to re-open gomuks later on, I get the following error:
![2020-11-11-122935_519x133_scrot](https://user-images.githubusercontent.com/17123948/98806517-9bb45080-2419-11eb-884e-7cecbb6bb343.png)

I am using the latest AUR `gomuks` package. Is there any additional information I can provide to help provide the issue, before I wipe the state and start again ?

**Comment by tulir** [comment]
#246
