### ISSUE TITLE
Build fails after blackfriday/v2 package cannot be downloaded.

### ISSUE THREAD

**Issue by mgiagante** [tulir/gomuks#249]
➜  gomuks git:(master) ✗ go get -v
github.com/russross/blackfriday (download)
package github.com/russross/blackfriday/v2: cannot find package "github.com/russross/blackfriday/v2" in any of:
	/usr/lib/go-1.10/src/github.com/russross/blackfriday/v2 (from $GOROOT)
	/home/mg/go/src/github.com/russross/blackfriday/v2 (from $GOPATH)
➜  gomuks git:(master) ✗ go build
../go/src/maunium.net/go/mautrix/format/markdown.go:14:2: cannot find package "github.com/russross/blackfriday/v2" in any of:
	/usr/lib/go-1.10/src/github.com/russross/blackfriday/v2 (from $GOROOT)
	/home/mg/go/src/github.com/russross/blackfriday/v2 (from $GOPATH)

**Comment by mgiagante** [comment]
Following the URL for the v2 version I found a 404 page. Apparently it was moved in Github.
The URL for the v1 version does work.

**Comment by tulir** [comment]
> go-1.10

Sounds like your Go is outdated

**Comment by mgiagante** [comment]
Thank you @tulir . I'll update it.
