### ISSUE TITLE
Long passwords cannot be entered in the password field

### ISSUE THREAD

**Issue by cdutsov** [tulir/gomuks#254]
I have a 30+ characters password and it cannot be entered in the password field. I tried to log in with another account on the same server with a short password and it's working fine.

Thanks for the nice piece of software!

**Comment by cdutsov** [comment]
it seems that the issue is resolved

**Comment by caminsha** [comment]
I tried to use gomuks with some different password lengths and unfortunately I could not log in with passwords that are too long. During my test it was no problem to login with passwords arount 100 characters but I could not login with passwords around 120 characters.

The passwords were all generated and did not contain any special charachters. The only characters were letters (small and capital) and numbers.

I could not find out which length is still supported and which not.

I tested the login process with the current master branch and the latest release.
Operating System: Fedora 33

**Comment by sagehane** [comment]
I decided to test this a bit, using the debug log described in #247 to check how passwords were being parsed. (Speaking of which, the location of the log was `/run/user/<id>/gomuks/debug.log` on NixOS.)

All the passwords shown were generated by KeePassXC:

---
Password 1 (128 long, extended ASCII):
```
ý£Ü8ÂQ¸ék])à¿I\Åÿ±Öo¢\'À½Z¦#¨ÑD1/N'1Ä<üËû5¾Zjl'¥í4|rh¦T÷e·8Y¾¹t8×½£¦Áz&FkVx¶ômÉ;.EUo1yDí7p~µ´±ku[¶ß`Gx/ni³(]ËÝ()?òQ/W®HfS+(z±¦ÆØ`
```
Output:
```
POST https://matrix.org/_matrix/client/r0/login {"type":"m.login.password","identifier":{"type":"m.id.user","user":"test"},"password":"1yDí7p~µ´±ku[¶ß`Gx/ni³(]ËÝ()?òQ/W®HfS+(z±¦ÆØ[201~Ëû5¾Zjl'¥í4|rh¦T÷e·8Y¾¹t8×½£¦Áz\u0026FkVx¶ômÉ;.EUo1yDí7p~µ´±ku[¶ß`Gx/ni³(]ËÝ()?òQ/W®HfS+(z±¦ÆØ[201~","initial_device_display_name":"gomuks"}
```
What even is going on here? Parts of the password starts being looped around?

---
Password 2 (64 long, extended ASCII):
```
"bP"(äÊò¶^]ô'yiµÜûW³¢Hç)>Ý&jðÁË@ã¨-ÅÌm¦Ï${åJP0µì:ùQ¨HW9<ô@îùÓDv*
```
Output:
```
POST https://matrix.org/_matrix/client/r0/login {"type":"m.login.password","identifier":{"type":"m.id.user","user":"test"},"password":"\"bP\"(äÊò¶^]ô'yiµÜûW³¢Hç)\u003eÝ\u0026jðÁË@ã¨-ÅÌm¦Ï${åJP0µì:ùQ¨HW9\u003cô@îùÓDv*","initial_device_display_name":"gomuks"}
```
This looks somewhat correct. Seems like some characters got escaped for some reason. (I have no idea if this affects one's capacity to long, too lazy to actually change my account password to test)

---
Password 3 (128 long, no extended ASCII):
```
TN%Sf1Fd@Q(P6#P*f~Hf=|SoM,)gpqN$k:}Z39H:|dcYcL'j+fGJN9Lnof)vL{E0`Q85,KpPVoNU\?NwP^(mx/1]yrFK_VRP.W:xCb9rme2CKTS[0a]|y?qCk*-D;:O\
```
Output:
```
POST https://matrix.org/_matrix/client/r0/login {"type":"m.login.password","identifier":{"type":"m.id.user","user":"test"},"password":"-D;:O\\[201~Fd@Q(P6#P*f~Hf=|SoM,)gpqN$k:}Z39H:|dcYcL'j+fGJN9Lnof)vL{E0`Q85,KpPVoNU\\?NwP^(mx/1]yrFK_VRP.W:xCb9rme2CKTS[0a]|y?qCk*-D;:O\\[201~","initial_device_display_name":"gomuks"}
```
The beginning and end seems to loop with 128 long passwords.

---
Password 4 (116 long, alphanumerals):
```
R3ec8Y1iCmtddh8uSmNCu6oYoX1J0sFrdhCm1ROA9iUaeusPz0whij2LUveAwmkiNafcSCMRqc2v1NifPCNIW5FokCIoadjZgYcIOcKjgT9j4OZ8ja48
```
Output:
```
POST https://matrix.org/_matrix/client/r0/login {"type":"m.login.password","identifier":{"type":"m.id.user","user":"test"},"password":"R3ec8Y1iCmtddh8uSmNCu6oYoX1J0sFrdhCm1ROA9iUaeusPz0whij2LUveAwmkiNafcSCMRqc2v1NifPCNIW5FokCIoadjZgYcIOcKjgT9j4OZ8ja48","initial_device_display_name":"gomuks"}
```
Finally, it seems to work. I tried passwords with a length of 117 and higher, and it consistently seems to glitch. Implying 116 is the limit. Works fine with a non-extended ASCII password, but a 116 long extended-ASCII password still seems to wrap around.

---
I hope that helps. As a person who uses a 128 long extended ASCII password for everything, I wish this would be addressed.
