### ISSUE TITLE
Failed to initialize crypto

### ISSUE THREAD

**Issue by VictorNine** [tulir/gomuks#258]
When trying to log in to the feneas.org homeserver i get the following error. "failed to initialize crypto: failed to open crypto store: extra data in buffer."

Running on linux amd64 v0.2.2

**Comment by linuxclowns** [comment]
Getting the same here. Debian 10, gomuks v0.2.2

**Comment by VictorNine** [comment]
Looks like crypto.gob has been corrupted some how. Probably something changed in the new version. rm -r ~/.local/share/gomuks/ fixes the problem.

I'll leave it open since there might still be some bug here

**Comment by linuxclowns** [comment]
Deleting crypto.gob did not fix the issue for me.

**Comment by linuxclowns** [comment]
Deleting both ~/.local/share/gomuks and ~/.cache/gomuks sorted it for me.

**Comment by VictorNine** [comment]
Closed with ref to https://github.com/tulir/gomuks/issues/246
