### ISSUE TITLE
Create direct message rooms

### ISSUE THREAD

**Issue by gsauthof** [tulir/gomuks#259]
When I use `\pm some_element_io_user ...` the result for that user is that he gets an invite to a standard room, i.e. and not to a 'Direct Messages' room.

IOW, that private room is then listed under the 'Rooms' tab and not under the 'Direct Messages' tab.

So, using gomuks, is there some way to invite a user to a DM room?

Perhaps some room attribute is missing that marks such room as DM for clients that decide to list them differently.

**Comment by gsauthof** [comment]
I think it's a matter of setting the `is_direct` flag on `createRoom`:

- https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-createroom
- https://matrix.org/docs/spec/client_server/latest#module-dm
- https://godoc.org/maunium.net/go/mautrix#ReqCreateRoom

I've tested it locally and it works as expected. Pull-request follows.

**Comment by divVerent** [comment]
That patch doesn't appear to be everything - private rooms still show up as "room" and not "people" both in gomuks and the Element client.

**Comment by divVerent** [comment]
Is it maybe this part that is missing?

https://github.com/matrix-org/matrix-doc/pull/389/files
> Both the inviting client and the invitee's client should record the fact that the room is a direct chat by storing an m.direct event in the account data using /user/<user_id>/account_data/<type>.

**Comment by gsauthof** [comment]
Perhaps, I just tested the direction gomuks -> element.io (on Android) and this worked for me. Perhaps also depends on the home server.
