### ISSUE TITLE
Trying to install `gomuks` fails with a `blackfriday` error.

### ISSUE THREAD

**Issue by MacLemon** [tulir/gomuks#262]
# Summary:
Trying to install `gomuks` fails with a `blackfriday` error.

## Steps to Reproduce:
- `go get github.com/tulir/gomuks`

## Expected Results:
Installation and building should succeed without error.

## Actual Results:
Installation fails with this error message:

```shell
$ go get github.com/tulir/gomuks
cannot find package "github.com/russross/blackfriday/v2" in any of:
        /usr/local/go/src/github.com/russross/blackfriday/v2 (from $GOROOT)
        /home/<username>/go/src/github.com/russross/blackfriday/v2 (from $GOPATH)
```

Trying to install just `blackfriday/v2` results in this:
```shell
$ go get github.com/russross/blackfriday/v2
cannot find package "github.com/russross/blackfriday/v2" in any of:
        /opt/local/lib/go/src/github.com/russross/blackfriday/v2 (from $GOROOT)
        /Users/MacLemon/go/src/github.com/russross/blackfriday/v2 (from $GOPATH)
```

Trying to install just `blackfriday` seems to work just fine:
```shell
$ go get github.com/russross/blackfriday
$ echo $?
0
```

## Regression:
Given that there are people who actively use `gomuks` I asume this did work at some point.
Manually building `gomuks` from source *seems* to work. (`lib/olm` is provided and is found by `go build`.)

This results in a `gomuks` binary that can be launched. It asks for login credentials, and *seems* to login. The only UI I get is the white vertical bar which separates the room list from the chat area. It doesn't react to any input, and also seems to catch ⌃C.

## Notes:
I'd need `gomuks` to test for `pingpong`/[Issue 8](https://github.com/p-e-w/pingpong/issues/8) so we can rule out a possible problem with between `pingpong` and `mautrix`.

## Version Information:
Installation tried on
- macOS 10.13.6
  - `go 1.15.6 darwin/amd64`
- FreeBSD 12.2-p2
  - `go 1.15.7 freebsd/amd64`
- Arch Linux
  - `go 1.15.7 linux/amd64`

**Comment by tulir** [comment]
`go get` is essentially legacy and shouldn't be used for installing programs that use Go modules. The proper way to build from source is to `git clone` and `go build` like the wiki says.

If you really want to use go get for some reason, you have to set `GO111MODULE=on` and use the correct import path (`maunium.net/go/gomuks`)
