### ISSUE TITLE
Add HTML table rendering and improve code blocks

### ISSUE THREAD

**Issue by tulir** [tulir/gomuks#27]
Code blocks and HTML tables could be rendered in a way that limits their width and height and instead allows selecting the message and scrolling it horizontally and vertically.

Requires #26

**Comment by Huy-Ngo** [comment]
Maybe covered by this issue: newlines aren't displayed in the message.

![Some CSS where the newlines aren't displayed](https://user-images.githubusercontent.com/19296926/109264667-ee364300-7837-11eb-9ed5-c2b48712c34f.png)

Also as #26 is closed, shouldn't the label "blocked" be removed?
