### ISSUE TITLE
Properly break on words

### ISSUE THREAD

**Issue by Phenitei** [tulir/gomuks#273]
Hi,

Thank you for your work on gomuks! This issue is a feature request: it would be great if, when wrapping a line in the room interface, gomuks could recognize a word and wrap at the previous word separation before hitting the line length limit. Currently, lines are just split after n chars, which make reading long messages not very comfortable.

Because implementing language recognition and the propper splitting rules for every written system, though ideal, is afaik impossible, simply wrapping on spaces instead of a fixed length seems like a good idea and would go a long way towards making things more readable.

Best,

**Comment by tulir** [comment]
Lines are already split on spaces (except when something is broken)

**Comment by Phenitei** [comment]
Then something is broken :)
Using `gomuks version v0.2.3` from the AUR on archlinux:
![2021-03-16-142606_1269x97_scrot](https://user-images.githubusercontent.com/17123948/111316685-c3cfec80-8663-11eb-91ae-59f5d2bbab90.png)

(two examples: the first line of the paste is a split in the middle of the french word "assez" and the end of the first line splits the french word "était").

Can I provide any additional information to help debug this issue ?

**Comment by n-peugnet** [comment]
I have the same problem with french words. It does not seem to happen with english words.

I am on gomuks 0.2.3-1 from the release's debian package.

**Comment by drasbeck** [comment]
Unsurprisingly lines also breaks badly on Danish words. Just adding my voice to the discussion.
I have seen this behavior for many versions of gomuks across a handful of operating systems and a wealth of terminal emulators.

Version: gomuks 0.2.3 amd64 binary from this repo, running on WSL2 Debian 10, shown by Windows Terminal v. 1.7.1033.0

**Comment by 4censord** [comment]
I also have this issue, although with German writing.
It seems to be related to non ASCII caracters?
with this lorem ipsum it propperly breaks on spaces for me.

```text
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
```

With the same text, but some `u` replaced by `ü`, the german umlaut, it no longer breakes on spaces.
```text
Lorem Ipsüm is simply dümmy text of the printing and typesetting indüstry. Lorem Ipsüm has been the indüstry's standard dümmy text ever since the 1500s, when an ünknown printer took a galley of type and scrambled it to make a type specimen book.
```

![20211014_10h06m32s_grim](https://user-images.githubusercontent.com/49623362/137276669-2c16bee5-62ee-4f04-9e06-8a96d494f509.png)

This effect can be seen even when editting a message to include a non ascii character, 
only tested with `öäüéèê` cause those are on my keyboard,

Without umlauts
![20211014_10h02m28s_grim](https://user-images.githubusercontent.com/49623362/137276269-f166b8f9-abdd-474b-8aa9-3397c7785a2b.png)

With the `e` in the first text replaced by `é`
![20211014_10h03m31s_grim](https://user-images.githubusercontent.com/49623362/137276256-faf5a373-0c89-45fb-aa46-030997fde159.png)


This is on Arch linux 5.14.11-arch1-1,
With gomuks v0.2.4
