### ISSUE TITLE
How does someone disable notifications?

### ISSUE THREAD

**Issue by JimPix1** [tulir/gomuks#275]
These notifications are a HUGE pain in the ass, theyre like dunst but bigger, appear on every workspace, stack on top of eachother and always appear if you're not using gomuks as the focused window.
How do I disable them entirely? Like, I just don't want notifications whatsoever, I can't seem to find a way of turning them off anywhere.

**Comment by Evidlo** [comment]
That happens in [notify_linux.go](https://github.com/tulir/gomuks/blob/master/lib/notification/notify_linux.go#L22-L37).  You can disable them and recompile, or make a PR to add the config option yourself.

If you make a PR, you might use [this PR](https://github.com/tulir/gomuks/pull/111) as a guide.

**Comment by tulir** [comment]
[`/toggle notifications`](https://github.com/tulir/gomuks/wiki/Commands)
