### ISSUE TITLE
cant copy markdown messages

### ISSUE THREAD

**Issue by georgkrause** [tulir/gomuks#276]
Steps to reproduce: Send a message with some markdown, eg `# test`. Try to copy it. It does not work, if you paste, the previous copied message will be pasted

**Comment by Ulexus** [comment]
I have not tried, but I assume this will work if you switch to raw mode (<ctrl>+l) first.

**Comment by georgkrause** [comment]
@Ulexus This works, but is more a workaround than a fix. thanks for the hint anyway :)

**Comment by Ulexus** [comment]
Agreed; it is just a useful method for all sorts of similar issues.
