### ISSUE TITLE
Dates in « Date changed to » are wrong

### ISSUE THREAD

**Issue by Phenitei** [tulir/gomuks#277]
Hi there,

Thank you for your work on gomuks! It seems that the dates that are shown in the IRC-like  « date changed » messages are wrong: they are incremented by one with respect to the previous day, so if a room wasn't opened for a few days, then the date is off.

As an example, I have three different rooms telling me today that we are the 19th, the 13th and February 23d...

**Comment by tulir** [comment]
Those don't appear automatically, they work the same way as date separators in Element: if a message is on a different day than the previous message, a separator with the new message's date is inserted in between

**Comment by Phenitei** [comment]
Yes, but - as far as I can tell, said date is wrong. The examples above are all from messages I have received today (2021-03-19).

**Comment by tulir** [comment]
Maybe you received old messages? There's no incrementing going on, it simply renders the date of the new message if the previous message was on a different date.

**Comment by Phenitei** [comment]
So, I'm not completly certain of this increment thing - I just noticed that on all my examples, the printed date was the previous one + 1 day.

 I am, however, completely certain that the messages were all sent on the same day: the 19th was my birthday. All messages screenshotted below were recieved that day - notice the dates being off each time (I have a bunch more, with dates ranging from the correct day to February 2nd).
 
![2021-03-22-163253_545x61_scrot](https://user-images.githubusercontent.com/17123948/112015815-743e6480-8b2c-11eb-815f-b2769f26c17b.png)
![2021-03-22-163211_569x46_scrot](https://user-images.githubusercontent.com/17123948/112015820-74d6fb00-8b2c-11eb-8129-2149c8c8edab.png)
![2021-03-22-163141_508x118_scrot](https://user-images.githubusercontent.com/17123948/112015822-756f9180-8b2c-11eb-84e3-b045e2150d52.png)

**Comment by julianuu** [comment]
I can confirm. If in element web a conversation looks like this
```
        date1
message1
        date2
message2
        date3
message3
```
then in gomuks it shows as
```
message1
Date changed to date1
message2
Date changed to date2
message3
```
and I think it element web it shows the dates correctly.
