### ISSUE TITLE
Crash immediately on start

### ISSUE THREAD

**Issue by Xartos** [tulir/gomuks#286]
I just switched to a new terminal, `foot`, from `termite`

in `termite` everything works fine, but now when I switched the program panics as soon as I start it.

I tried both the release and building it from master with the same issue.  

```console
$ DEBUG=1 ./gomuks 
panic: exit status 1 [recovered]
        panic: exit status 1

goroutine 1 [running]:
maunium.net/go/gomuks/debug.Recover()
        /home/freddeliv/privat/gomuks/debug/debug.go:109 +0xe8
panic(0x138e620, 0xc0003cb240)
        /usr/lib/go-1.14/src/runtime/panic.go:975 +0x3e3
main.(*Gomuks).Start(0xc000680570)
        /home/freddeliv/privat/gomuks/gomuks.go:116 +0x1b9
main.main()
        /home/freddeliv/privat/gomuks/main.go:88 +0x79d
```

**Comment by Coding-Boon** [comment]
Hey,

i had the same issue.

rm -rf /home/--mylocaluser--/.cache/gomuks fixed the problem

**Comment by Xartos** [comment]
Aah, thanks! Unfortunately that doesn't work for me
