### ISSUE TITLE
Types strange characters in message field when fast scrolling through history

### ISSUE THREAD

**Issue by andrewrothman** [tulir/gomuks#288]
I am using a Logitech MX Master 3 with Logi Options software on Mac.

Slowly scrolling through the history works perfectly, but fast scrolling starts to produce these characters in the "Send a message..." field. When I stop scrolling, they stop (sometimes after a delay).

OS: macOs Catalina 10.15
Terminal: Alacritty
Happens regardless of whether `gomuks` is running inside `tmux` or not.

Example:
```
;44M4;61;44M4;61;44M4;61;44M4;61;44M;44M4;61;44M;44M4;61;44M;44M4;61;44M;44M4;61;44M;44M4;61;44M4;61;44M4;61;44M4;61;44M;44M4;61;44M;44M4;61;44M;44M4;61;44M;44M4;61;44M;44M4;61;44M;44M4;61;44M;44M4;61;44M;44M4;61;44M;44M4;61;44M;44M4;61;44M;44M4;61;44M
```

In this video, I am running `gomuks` without using `tmux`:

https://user-images.githubusercontent.com/742678/118376487-f96a5680-b57c-11eb-80f0-d9d9c2f9807b.mov

**Comment by r3k2** [comment]
This has happened to me as well many times, also sometimes when I copy a url with ctrl+c and paste with ctrl+shift+v it pastes with garbage at the start and end and breaks the url

**Comment by brunofontes** [comment]
They also appear to me in other scenarios, as just moving the mouse around without clicking or scrolling.
