### ISSUE TITLE
how to get encryped messages to work?

### ISSUE THREAD

**Issue by autoteelar** [tulir/gomuks#290]
im verified but all my messages wont re check its still cant find
![image](https://user-images.githubusercontent.com/76745649/118874985-84b75500-b8b9-11eb-9f75-1519b431a06d.png)

**Comment by mradigen** [comment]
@kohfuchs I'm guessing you meant `/clearcache`? Running `/clearcache` and starting `gomuks` again doesn't solve the issue for me. Let me know if any particular logs or debug info is required!

**Comment by kohfuchs** [comment]
@mradigen yes, you are right! Sorry for that!

Ok i see, you need to verify gomuks with key, downloaded via Element:

For Element, you can go into `all settings > security & privacy > export e2e room keys`. Then in `gomuks`, use the `/import ` command.

**Comment by tjex** [comment]
@autoteelar pls close this if the issue has been resolved
