### ISSUE TITLE
Failed to import sessions: invalid Matrix key export: missing prefix

### ISSUE THREAD

**Issue by les-citrons** [tulir/gomuks#291]
I am unable to import keys from element due to encountering this error: 
`Failed to import sessions: invalid Matrix key export: missing prefix`

**Comment by les-citrons** [comment]
upon investigation, this appears to be due to element using \r\n newlines

**Comment by airpods69** [comment]
not sure but what would the fix be for this? im still facing the issue

**Comment by apprehensions** [comment]
same

**Comment by Wolfbeta** [comment]
Use the web client at element.io to export.
