### ISSUE TITLE
Ordering of Rooms in Quick Room Switcher

### ISSUE THREAD

**Issue by khdlr** [tulir/gomuks#309]
How do the rooms get sorted in the quick room switcher? It appears to be neither alphabetical, nor by recent activity (in the screenshot below, Test Room C has the most recent messages)

![Screenshot_20210901_130658](https://user-images.githubusercontent.com/9249838/131661125-7d045ede-3ac9-4b16-bf4d-13c8b99d743d.png)

Not 100% sure, but it looks like they're sorted by time of creation. Is that what's happening here?

In any case, the current sorting method doesn't feel really intuitive.

**Comment by tinsel-grumble** [comment]
room sort also broke on sidebar, and change random. how to change there too?
