### ISSUE TITLE
Feature Request: Edit in External Editor

### ISSUE THREAD

**Issue by jgarte** [tulir/gomuks#311]
Is it in the scope of this project to add this feature?

I would like to be able to just open the buffer in vim to compose my message instead of using the built in editing.

WDYT?

**Comment by Flammable-Duck** [comment]
That could be super handy, especially for longer messages/formatting

**Comment by begss** [comment]
Ok, I wrote an initial implementation in one evening, but it uses a separate terminal emulator. Anyone have an idea on how to open `vim` or whatever `$VISUAL` is on another tcell's screen or something like that?

cc @tulir
