### ISSUE TITLE
`A fatal error has occurred`: `unexpected end of JSON input`

### ISSUE THREAD

**Issue by AnInternetTroll** [tulir/gomuks#315]
I started `gomuks` from the terminal after 2 days of not using it and I got this error:
```console
 __________
< Oh noes! >
 ‾‾‾\‾‾‾‾‾‾
     \   ^__^
      \  (XX)\_______
         (__)\       )\/\
          U  ||----W |
             ||     ||

A fatal error has occurred.

The stack trace has been saved to /tmp/gomuks/panic-2021-10-10--12-43-26.txt

You can file an issue at https://github.com/tulir/gomuks/issues.
Please provide the contents of that file when filing an issue.
```

```go
unexpected end of JSON input
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
maunium.net/go/gomuks/debug.PrettyPanic({0xcccde0, 0xc00061c840})
	debug/debug.go:133 +0x1b1
maunium.net/go/gomuks/debug.Recover()
	debug/debug.go:107 +0x5a
panic({0xcccde0, 0xc00061c840})
	/usr/lib/go/src/runtime/panic.go:1038 +0x215
maunium.net/go/gomuks/config.(*Config).load(0xc000132c80, {0xdadfb2, 0xa}, {0xc000028a68, 0x18}, {0xdc9e65, 0x41a107}, {0xc87e40, 0xc000132da0})
	config/config.go:231 +0x3bd
maunium.net/go/gomuks/config.(*Config).LoadPushRules(...)
	config/config.go:197
maunium.net/go/gomuks/config.(*Config).LoadAll(0xc000132c80)
	config/config.go:149 +0x225
main.NewGomuks(0xe60280, {0xc000094920, 0x19}, {0xc000094940, 0x1e}, {0xc000028900, 0x18}, {0xc00009e000, 0x14})
	gomuks.go:50 +0x174
main.main()
	main.go:82 +0x567
```
Other maybe relevant stuff
```console
$ uname -a
Linux chell 5.14.9-zen2-1-zen #1 ZEN SMP PREEMPT Fri, 01 Oct 2021 19:03:23 +0000 x86_64 GNU/Linux
```

**Comment by pataquets** [comment]
Fixed the error for me, too. My file was not empty, but truncated.
A message stating the file would be helpful.
Also, not even the `-v` switch worked, which I was using to check for an updatedb version.

**Comment by bwildenhain** [comment]
I just had the same issue using the current Debian  package gomuks 0.2.4-1: Empty pushrules file and failing to start with the following message:

unexpected end of JSON input
goroutine 1 [running]:
runtime/debug.Stack(0x13f0ce0, 0xc0000bbf50, 0xc00053f9f8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
maunium.net/go/gomuks/debug.PrettyPanic(0xe73c80, 0xc0000bc738)
        /builds/tulir/gomuks/debug/debug.go:133 +0x245
maunium.net/go/gomuks/debug.Recover()
        /builds/tulir/gomuks/debug/debug.go:107 +0x65
panic(0xe73c80, 0xc0000bc738)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
maunium.net/go/gomuks/config.(*Config).load(0xc000022dc0, 0xf7599a, 0xa, 0xc00002a450, 0x28, 0xf91868, 0xe, 0xe21a40, 0xc000022ee0)
        /builds/tulir/gomuks/config/config.go:231 +0x576
maunium.net/go/gomuks/config.(*Config).LoadPushRules(...)
        /builds/tulir/gomuks/config/config.go:197
maunium.net/go/gomuks/config.(*Config).LoadAll(0xc000022dc0)
        /builds/tulir/gomuks/config/config.go:149 +0x23c
main.NewGomuks(0x10267c8, 0xc00002a1e0, 0x29, 0xc00002a240, 0x2e, 0xc00002a2a0, 0x28, 0xc0000280c0, 0x1a, 0x4441ea)
        /builds/tulir/gomuks/gomuks.go:50 +0x17c
main.main()
        /builds/tulir/gomuks/main.go:82 +0x6ca
