### ISSUE TITLE
Colored messages from IRC are not readable

### ISSUE THREAD

**Issue by sebihotza** [tulir/gomuks#316]
We have a Matrix-IRC-Discord bridge that sends messages from IRC to Matrix as `[^C13username^C00^C] message content`. So messages should look like:
![image](https://user-images.githubusercontent.com/61342411/137630106-fa51a970-a284-4946-828d-344a3fdca026.png)
However, parts after `^C` of messages are not readable in gomuks:
![image3](https://user-images.githubusercontent.com/61342411/137630178-03892582-28f9-4e03-b9a5-2899c280c0a6.png)
I tried with another terminal and font but the issue persists, have no idea why this is happening.

**Comment by tulir** [comment]
gomuks doesn't do anything related to IRC, but there may be bugs in the HTML renderer. The event content is needed to debug those (view source in the message context menu on element, currently no way to get it from gomuks)
