### ISSUE TITLE
Build on FreeBSD and Windows 10 fails, cannot find olm.h

### ISSUE THREAD

**Issue by lpvm** [tulir/gomuks#321]
I'm trying to build gomuks on a FreeBSD 13.0-RELEASE amd64 system.
The package olm is installed.
`olm.h` is at `/usr/local/include/olm/olm.h`

When doing `go build`  the process stops at:
```
# maunium.net/go/mautrix/crypto/olm
../../prog/go/pkg/mod/maunium.net/go/mautrix@v0.9.29/crypto/olm/account.go:4:11: fatal error: 'olm/olm.h' file not found
 #include <olm/olm.h>
          ^~~~~~~~~~~
1 error generated.
```
How to have the path for `olm.h` known to the build process?

**Comment by sys-256** [comment]
+1, I have the same error when building on Windows 10 (19042.870).

```
$ go build
# maunium.net/go/mautrix/crypto/olm
C:\Users\Bram\go\pkg\mod\maunium.net\go\mautrix@v0.9.29\crypto\olm\account.go:4:11: fatal error: olm/olm.h: No such file or directory
    4 | // #include <olm/olm.h>
      |           ^~~~~~~~~~~
compilation terminated.
                                                                                                                                                      powershell | 21:29:38
$
```

**Comment by Tycho-S** [comment]
On FreeBSD just install the olm package and then build as such:

```CGO_LDFLAGS='-L/usr/local/lib' CGO_CFLAGS='-I/usr/local/include/' go build -x```

**Comment by lpvm** [comment]
Thank you @Tycho-S.
It builds fine with the suggested command.
Thank you very much.
