### ISSUE TITLE
Option for disabling mouse support with /toggle

### ISSUE THREAD

**Issue by TheWing** [tulir/gomuks#326]
Hi.

Mouse support seems to get messed up with at least rxvt-unicode, and even though as a workaround one can disable mouse handling from the terminal side, it would probably be good to have a /toggle option for mouse as well.

At least personally I don't require mouse interactions, as long as there are ways to do things with the keyboard as well. I'm not sure which features aren't currently doable without a mouse, but it does seem that at least replying isn't easily possible?

**Comment by Toasterbirb** [comment]
I also have a problem with the mouse support. Focusing the window with mouse and moving the cursor over the terminal window adds random text like this ";55M<35;195;55M<35;195;55M6M<35;179;56M6M<35;162;56M5M<35;148;55M4M<35;135;55M" to the message box.

Would be nice to be able to disable mouse support completely until a solution can be found for these issues

**Comment by xaionaro** [comment]
Heh. I see this bug if I run gomuks from alacritty, but I see no bug if I run from konsole.

**Comment by xaionaro** [comment]
I've just tried to run alacritty in a debugging mode and the problem disappeared. Looks like a race condition in gomuks?

**Comment by divVerent** [comment]
I agree - I am using gomuks under tmux under rxvt-unicode, and frequently get annoyed by this mouse support.

I just want it gone.

**Comment by okt** [comment]
Can also report that I am experiencing similar output from within kitty both in OpenBSD and Arch Linux. 

kitty 0.24.4
gomuks v0.2.4

**Comment by arzam16** [comment]
I've got the same issue as @Toasterbirb . In my case `gomuks` is installed on a Debian 11 remote machine that I access via SSH from `GNOME Terminal 3.44.0 VTE version 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD`. When I move the mouse cursor over any TUI element in gomuks, the message input field gets spammed with those weird codes real quick. And it gets even worse when I hit Shift+PrtSc (the default "screenshot of a selection" hotkey in Linux Mint) - the amount of these codes is very high. Interesting though, I cannot reproduce it every time, I'd rather say the repr. rate is about 90%. But even if this "feature" didn't appear right away it might show up later.

@tulir , could you please look into this issue?

**Comment by mml** [comment]
I see this in both xterm and urxvt, with screen running inside the terminal.  @tulir what's involved in fixing this?  I'm happy to send a patch but a pointer to the relevant parts of the code would help me get started.
