### ISSUE TITLE
failed to decrypt previous massages

### ISSUE THREAD

**Issue by mrbooshehri** [tulir/gomuks#330]
despite my account is verified the program cannot decrypt my previous messages and shows the following message for each message. Also I checked this #267 issue and as it said enter ```/clearcahce``` command in the program but it made no difference.

```failed to decrypt megolm event: no session with given ID found (ID .....)```

**Comment by Whodiduexpect** [comment]
I had this issue too but importing encryption keys from Element then clearing the cache in gomuks fixed it.

**Comment by mrbooshehri** [comment]
> I had this issue too but importing encryption keys from Element then clearing the cache in gomuks fixed it.

Thanks a lot it solved the problem.

solution:
```/import <ABSOLUTE_PATH_TO_KEY_FILE>```
