### ISSUE TITLE
Pasting should create a single message with multiple lines

### ISSUE THREAD

**Issue by Alzarath** [tulir/gomuks#337]
Current behavior: Pasting immediately sends a message for each line of the pasted text. Sufficiently large pastes can become very troublesome.

**Comment by tulir** [comment]
The current behavior is creating a single message with multiple lines. If your terminal doesn't support bracketed paste, install xclip, xsel or wl-copy and use ctrl+v instead of ctrl+shift+v/shift+insert (ctrl+v bypasses the terminal and reads the clipboard directly)

**Comment by Alzarath** [comment]
Right, I forgot I switched to a terminal that has Ctrl+V functionality. I've been so used to using Ctrl+Shift+V. All this clipboard stuff is confusing. Thanks.
