### ISSUE TITLE
Emojis are displayed as "?" characters

### ISSUE THREAD

**Issue by DigitalNXZ** [tulir/gomuks#338]
Hi~
so i couldn't find a issue 'bout this, so i'm really sorry if this is a duplicate!..
![image](https://user-images.githubusercontent.com/53005759/150406325-ef246c95-bcef-4971-982f-758290fb8c76.png)

I'm using windows~
Is it normal? at least on windows or is this just a bug on my side?

**Comment by emdete** [comment]
probably the terminal you're using. it doesnt support unicode. i switched to gnome-terminal out of that reason.

**Comment by DigitalNXZ** [comment]
> probably the terminal you're using. it doesnt support unicode. i switched to gnome-terminal out of that reason.

well aright if it depends on the terminal already installed on my pc (in this case windows), how can you change it? had the new windows terminal but it doesnt looked like it, more like the normal command promt?

**Comment by piotrvidal** [comment]
You could try downloading a windows terminal with unicode support, for example cmder.

**Comment by jjakob** [comment]
On GNU/Linux I found [kitty](https://sw.kovidgoyal.net/kitty/) works. It doesn't work on Windows though. urxvt didn't work, even though it has unicode in its name.

**Comment by pataquets** [comment]
Works on Linux with Alacritty terminal, and Noto Color Emoji font installed and configured as `monospace` fallback via fontconfig. Not just on gomuks, but on any terminal app.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
"http://github.com/alacritty/alacritty" and "http://github.com/googlefonts/noto-emoji" are able to provide what is necessary to remediate this.

**Comment by benmordecai** [comment]
On both Konsole and Alacritty with noto-fonts-emoji I am getting this: 
![image](https://user-images.githubusercontent.com/2068192/168453726-1fe461e4-a189-4d84-b08d-17bf1c8038e8.png)
