### ISSUE TITLE
Hangs while starting

### ISSUE THREAD

**Issue by waweic** [tulir/gomuks#339]
After logging in, gomuks just shows an infinite progress indicator. In the log, I find this message:

`[2022-01-28 10:41:32] Sync failed: request error: Get "https://matrix.my.domain/_matrix/client/r0/sync?filter=5&timeout=30000": unexpected EOF`

Deleting cache, config and data didn't help, I couldn't get it to work previously. I'm on a pinebook pro (arm) running postmarketOS / Alpine Linux

**Comment by andrewrunxiyu** [comment]
I think this is a Matrix server problem.  I just set up my Matrix server and I get the same issue.  I tried with other clients, same result.  You should report this to the developers of your Matrix server instead if this is the case.

**Comment by waweic** [comment]
I am not sure about that, other clients work perfectly fine on my server. It may be some combination though

**Comment by theksepyro** [comment]
I am having the same issue, also running gomuks from a pinebook pro (on Manjaro). I had been using gomuks on this machine for a while without issue, but recently reinstalled my homeserever using https://github.com/spantaleev/matrix-docker-ansible-deploy rather than from the debian package. Previously my server was at domain.xyz, but the docker-ansible-deploy sets the server up at matrix.domain.xyz while the username is at @username:doimain.xyz. Could those not being the same cause this problem somehow?

**Comment by jjakob** [comment]
I think the domain you host your server on and the server part after your username need to match.

**Comment by theksepyro** [comment]
> I think the domain you host your server on and the server part after your username need to match.

This is not the case. For example you can use gomuks to log to the reference matrix.org server which is at matrix-client.matrix.org, but the username is @username:matrix.org, so I'm thinking it's something else.

**Comment by waweic** [comment]
I am not sure that the public_baseurl variable actually does anything other than populating the value in the /.well-known/matrix/client file. I have the .well-known directory separate on another server with another domain, just like you do. 
I am not using the code from the directory you mentioned though, as I built my own.

I can now confirm that it doesn't only fail to connect on a Pinebook Pro running Alpine, it also fails on a "normal" Thinkpad running Arch. But it's a funny occurence that both of us use a Pinebook Pro. Or not so much, as most other Matrix Clients are *slow* on these things.

Another peculiar thing I discovered:
Both gomuks and the reverse proxy complain about an unexpected closing of the connection.

This is a line from the gomuks log:
`[2022-02-22 18:33:44] [Matrix] req #16: GET https://matrix.domain/_matrix/client/r0/sync?filter=5&timeout=3000`
And this is a line from the nginx log:
`192.168.178.10 - - [22/Feb/2022:17:51:16 +0000] "GET /_matrix/client/r0/sync?filter=5&timeout=30000 HTTP/2.0" 499 0 "-" "gomuks v0.2.4 (with mautrix-go v0.9.26)"`

There is another TLS proxy in between, but I've never had any problems with it whatsoever, so I wouldn't know why it might be a problem

**Comment by waweic** [comment]
I found my problem. It's far simpler than I assumed. My TLS proxy had a timeout setting, set to 3 seconds. This is by far not enough for the long polling that Matrix does. And apparently not long enough for Gomuks to do the first synchronization. It now starts fine
