### ISSUE TITLE
Document how to run multiple instances for different accounts

### ISSUE THREAD

**Issue by jjakob** [tulir/gomuks#342]
This is what I use:

```shell
alias gomuksaccount1='name=account1 GOMUKS_CACHE_HOME="~/.gomuks_$name/cache" GOMUKS_CONFIG_HOME="~/.gomuks_$name/config" GOMUKS_DATA_HOME="~/.gomuks_$name/data" DEBUG_DIR="/tmp/gomuks_$name" GOMUKS_DOWNLOAD_HOME="~/.gomuks_$name/downloads" gomuks'
```
Using GOMUKS_ROOT doesn't seem like a good idea to me as it could get overriden bx the XDG_ env variables, since gomuks checks those first.

I also have this to proxy through tor: 
```shell
alias tgomuks='HTTP_PROXY="socks5://127.0.0.1:9050" HTTPS_PROXY="$HTTP_PROXY" gomuks'
```

and a combination of those can be made by replacing gomuks with tgomuks in the first alias.

**Comment by tulir** [comment]
The order of preference is `GOMUKS_*_HOME` > `GOMUKS_ROOT` > system default (XDG)

**Comment by ElDifinitivo** [comment]
I have a quick shell function to do something similar. As long as the config file is created and the other dirs are listed there, all you need is `GOMUKS_CONFIG_HOME`.

This still needs to actually setup a new account if one's not listed and adding completion for homeservers is pending, but something like this works well, especially if you have many different accounts where it'd be a hassle to constantly make multiple aliases for each.

```fish
function mx
    set homeserver $argv[1]

    if test -z $homeserver
        printf "Please select a homeserver\n"
    else
        set config ~/.config/gomuks/$homeserver

        if test ! -d $config
            printf "Setting up $homeserver...\n"
            mkdir $config
        end

        set -gx GOMUKS_CONFIG_HOME $config
        gomuks

    end
end
```

**Comment by jjakob** [comment]
@ElDifinitivo 
Are you sure just setting GOMUKS_CONFIG_HOME is enough? You're still sharing cache, data, debug and download directories between the different processes, I don't think that's a good idea. Even if it works, you might want to completely delete all disk data for one homeserver, if you mix them it wouldn't be possible.
Even if you set GOMUKS_ROOT which changes the location of all XDG_ dirs, it still shares the download directory and debug log file (see https://github.com/tulir/gomuks/issues/307)
It is a good idea to have just one alias and use an env variable to change the directory names, I don't know why I didn't think of that.

**Comment by ElDifinitivo** [comment]
@jjakob As long as the lines in your config point to different dirs (with the exception of `download_dir`) then you're good. And yes like you said, it would be a good idea to pass a different debug dir, but separate download dirs don't seem necessary from my experience

```
data_dir: /home/<user>/.local/share/gomuks/<homserver>
cache_dir: /home/<user>/.cache/gomuks/<homserver>
history_path: /home/<user>/.cache/gomuks/<homserver>/history.db
room_list_path: /home/<user>/.cache/gomuks/<homserver>/rooms.gob.gz
media_dir: /home/<user>/.cache/gomuks/<homserver>/media
download_dir: /home/<user>/tmp
state_dir: /home/<user>/.cache/gomuks/<homserver>/state
```
