### ISSUE TITLE
Command Line Interface?

### ISSUE THREAD

**Issue by tdehaeze** [tulir/gomuks#344]
I guys,

I am wondering if it is planned to provide a command line interface?
It would be great to be able to get the number of un-read messages from a script for instance.

Thanks a lot

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Is that not all that this is?

**Comment by gi-yt** [comment]
there is a difference between 'TUI' and 'CLI'
a TUI means its a gui like thing operated with keyboard (have you seen ncurses dialog)
a CLI means you work with it through flags
there are many 'CLI' clients for matrix like matrixcli and matrix-commander
you can also use the matrix api to recieve and send messages

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Consequently, I support this, because it would significantly improve automation.

**Comment by jimt** [comment]
It would also be useful to allow sending a message to a user from the command line to replace **sendxmpp** / **go-sendxmpp**
