### ISSUE TITLE
Request error when trying to login

### ISSUE THREAD

**Issue by Miepee** [tulir/gomuks#345]
# Summary
I'm getting a request error regardless of what info I put into the login information

# Expected behavior
Instead of a request error, I should get appropriate responses, such as "Invalid password" for a wrong password", a successful login attempt with valid credentials, etc.

# Steps to reproduce
- Open Gomuks
- fill in example information in the login screen, such as `foo`, `bar`, `matrix.org`
- Click on Login

# Version information
- Gomuks: Linux Arm64 and Arm v.0.2.4
- System:
  - Android: 7.0
  - Ternux: 0.118.0
  - Model-number: BLN-21

**Comment by tulir** [comment]
Seems fine for me 🤔

![image](https://user-images.githubusercontent.com/4224639/156941657-4d101ee3-cf44-464b-9337-39d0b9e55d24.png)

**Comment by Miepee** [comment]
Hm, I can reproduce it reliably.
![image](https://user-images.githubusercontent.com/38186597/156996682-55258ef3-af81-4a82-ae3e-7fcb1ea95fae.png)
Did you test that on Termux? Might be a quirk specific to it.

**Comment by 4censord** [comment]
just to make sure it isn't DNS:

are you able to resolve and ping matrix.org?

```shell
dig A matrix.org
dig AAAA matrix.org
ping -4 matrix.org
ping -6 matrix.org
```

**Comment by 4censord** [comment]
and you are running on some kind of phone-like system, does your terminal have network permissions?

**Comment by Miepee** [comment]
Yes, I am running this on my phone, I even specified my model number in the initial post.

Termux does have internet access (as I was able to download the gomuks binary from there).
I am able to resolve matrix.org via ipv4, but not via ipv6.
In fact, I cannot resolve any ipv6 addresses, probably due to the fact that my ipv6 address is a link-local address.

**Comment by z8512** [comment]
Either you'll have to build it configuring path for termux environment or run inside proot. Common issue with all go application 

See https://stackoverflow.com/questions/38959067/dns-lookup-issue-when-running-my-go-app-in-termux

**Comment by Miepee** [comment]
Good to know. Closing this then, as it isn't a Gomuks issue.

**Comment by hardfau18** [comment]
even I am facing the same issue, i can ping using both ipv4 as well as ipv6

**Comment by Miepee** [comment]
You may wanna post specs, my issue was exclusive to android.
There was a comment in here that seems to have been deleted, but talked about how this is a thing exclusive to how Go doesn't work on android/termux and needs to be either recompiled for it or needs a special patch.

**Comment by 4censord** [comment]
I went digging through my email from back then, and found the now missing comment:

> Either you'll have to build it configuring path for termux environment or run inside proot. Common issue with all go application 
>
> See https://stackoverflow.com/questions/38959067/dns-lookup-issue-when-running-my-go-app-in-termux

If you are not running on an android device within termux you should probably open a new issue.

**Comment by hardfau18** [comment]
by manually building the application resolved the issue
