### ISSUE TITLE
Screen flickering and input problems

### ISSUE THREAD

**Issue by SchweinDeBurg** [tulir/gomuks#365]
After commit 89d5b0aa7bd02d45e2312717a9df82e98c39a507 there is screen flickering even if no new messages received and also persistent "q" letter in the input line and fuzzy search dialog. Commit a7562a068ad46839d18b01fa816c60362586999d looks and works perfectly well.

**Comment by n-peugnet** [comment]
There are at least 3 commits between https://github.com/tulir/gomuks/commit/89d5b0aa7bd02d45e2312717a9df82e98c39a507 and https://github.com/tulir/gomuks/commit/a7562a068ad46839d18b01fa816c60362586999d. I would suggest to use [git bisect](https://git-scm.com/docs/git-bisect) to find out which one is causing problems.

**Comment by tulir** [comment]
It's probably the tcell update, but doesn't happen for me, so not sure what's wrong with it

**Comment by SchweinDeBurg** [comment]
I am using Go version 1.17.8 - can it be a reason?

**Comment by tulir** [comment]
I was able to reproduce it on urxvt, but other terminals are fine. Still not sure what's up with it

**Comment by SchweinDeBurg** [comment]
I was able to reproduce it on plain Linux vritual console (runlevel 3) and on FBTerm2.

**Comment by jjakob** [comment]
It also happens on suckless st, but it's very slight and hardly noticeable.
