### ISSUE TITLE
"Invalid password" trying to login (including password changes)

### ISSUE THREAD

**Issue by Tcll** [tulir/gomuks#366]
my initial password was a level 4 security: (UTF-16)
`꼄⊻ꕋ淮㱛呏㟺糄礋ᦖ觊쌷蹨쭟ᗖ颖`

then I tried reducing that to level 3: (UTF-8)
`WÛQQðáÌÄcþ7øjàä®àÂSÆ±Å³$¤å£x]ù3Ì`

then level 2: (special characters)
`2Dp@<I8NXA2e+:i5B&laM$XZ&g?!McR^UqVxt?7g1@)_M#KEzGob~z-:0f pal C`

but not even level 1 security registered as valid: (alphanumeric)
`FXJAb6P6lnn6eq9DbdG9GPOABBUjoe5CDw0ftnA2weaOsBCHuSPnivmejJBfENR3PAAPENCCsNh9lLjS0waAiCCaGgVctzpOMBDhfnx6sp6SeEWkbexqBx1gtTm8MPfP`

btw, these were all generated for this issue
my actual passwords are typically much larger ;)

not sure what gomuks is doing, but the password input needs an overhaul

**Comment by tulir** [comment]
Probably duplicate of #165
