### ISSUE TITLE
Release schedule? Daily builds?

### ISSUE THREAD

**Issue by pataquets** [tulir/gomuks#372]
It's been quite a long time since last release and there are a bunch of interesting commits since then.
Aside from a release, is there any [soft] policy on releases?
What is the author's view on providing daily builds for testing bleeding edge with latest commits from master?

Docker has helped me a lot when tinkering with several projects independent of my host OS, without having to install any toolchain, and could double as a build/distribution method, too. For instance, it could help on #175.

**Comment by tulir** [comment]
CI builds have been around for years and are mentioned in the docs
