### ISSUE TITLE
Fatal error on start after installing on macOS via Homebrew

### ISSUE THREAD

**Issue by jakecoppinger** [tulir/gomuks#381]
Never used `gomuks` before.
Reached https://docs.mau.fi/gomuks/installation.html, followed link to https://github.com/aaronraimist/homebrew-tap.

Ran:
```
brew tap aaronraimist/tap
brew install gomuks
gomuks
```

Got error:
> A fatal error has occurred.

```
exit status 1
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x68
maunium.net/go/gomuks/debug.PrettyPanic({0x105393fe0, 0x14000384a60})
	maunium.net/go/gomuks/debug/debug.go:133 +0x14c
maunium.net/go/gomuks/debug.Recover()
	maunium.net/go/gomuks/debug/debug.go:107 +0x68
panic({0x105393fe0, 0x14000384a60})
	runtime/panic.go:838 +0x204
main.(*Gomuks).Start(0x14000444270)
	maunium.net/go/gomuks/gomuks.go:116 +0x15c
main.main()
	maunium.net/go/gomuks/main.go:89 +0x56c
```

On an M1 Mac. I haven't done any Go dev before.

Hope this helps :)

**Comment by jakecoppinger** [comment]
Ah - looks like a duplicate of https://github.com/tulir/gomuks/issues/250

**Comment by FiskFan1999** [comment]
@jakecoppinger can you try compiling from source? From looking around I can see that the [gomuks formula](https://github.com/aaronraimist/homebrew-tap/blob/master/gomuks.rb) from the homebrew tap is v0.2.4 which is from September last year. I'm compile gomuks from source  on the master branch and haven't experienced this (on intel chip though).
