### ISSUE TITLE
Move cache to ~/.cache

### ISSUE THREAD

**Issue by commagray** [tulir/gomuks#39]
Obvious, ~/.config isn't the place for pictures and history.

**Comment by tulir** [comment]
Good point. You can already change the history and media directories manually, but I guess room state should also be separated and they should all default to `~/.cache/gomuks/...`

**Comment by tulir** [comment]
The default for history/media is now `~/.cache/gomuks`, but existing configs won't be updated automatically. You can edit `~/.config/gomuks/config.yaml` and move the history and media directories manually.
