### ISSUE TITLE
(Ctrl+)Up/Down does not work

### ISSUE THREAD

**Issue by DUOLabs333** [tulir/gomuks#403]
When in a room, I can't use the Up and Down keys at all for anything. Other applications (on the terminal or not) still work.

**Comment by DUOLabs333** [comment]
It seems like gomuks is always focusing the text box. Maybe it should unfocus when clicked outside the text box?

**Comment by tulir** [comment]
It should never unfocus the text box except when selecting a message after a command like `/reply`. Up and down work as described in https://docs.mau.fi/gomuks/shortcuts.html. Ctrl might not work on all terminals, but alt should work in those cases

**Comment by DUOLabs333** [comment]
Alt doesn't work either.

**Comment by DUOLabs333** [comment]
Oh, it does, but not in Konsole (it works in xterm).
