### ISSUE TITLE
Cannot use it on Debian 11

### ISSUE THREAD

**Issue by Scorpion2185** [tulir/gomuks#405]
I tried the pre-built image, gomuks-linux-amd64, and I built it following the instructions.

After I login in it shows a vertical white line near the left edge and nothing more.

```
OS: Debian GNU/Linux 11 (bullseye) x86_64 
Kernel: 5.10.0-19-amd64 
```
Is the kernel maybe?

**Comment by tulir** [comment]
The OS isn't particularly relevant, but empty accounts aren't supported (#150).

**Comment by Scorpion2185** [comment]
@tulir Empty account?
I can use it, on gomuks, on another device.

**Comment by Scorpion2185** [comment]
@tulir The account is not empty, it is has some rooms and chats.
I can use it, on gomuks, on another device fine.

**Comment by tulir** [comment]
In that case, see https://docs.mau.fi/gomuks/debugging.html

**Comment by Scorpion2185** [comment]
I didn't see any error, I found this failure:
`Failed to store reaction in history db: event not found`.
In `/tmp/gomuks/debug.log`.

Is it just loading?
On my other device it showed a loading message.

`req` are raising: `[Matrix] req #75: `.

**Comment by Scorpion2185** [comment]
I didn't see any error, I found this failure:
`Failed to store reaction in history db: event not found`.
In `/tmp/gomuks/debug.log`.

Is it up to me to `To build and run with [race detection](https://golang.org/doc/articles/race_detector.html)`?

And then do I report here?
