### ISSUE TITLE
Pasting long text seems to result in truncated messages

### ISSUE THREAD

**Issue by Moult** [tulir/gomuks#406]
E.g. if I paste (via shift-insert) into gomuks "http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/concepts/Object_Association/Material_Association/Material_Constituent_Set/content.html#General-Usage" I get:

```
21:52:36 <Moult> check out erial_Constituent_Set/content.html#General-Usage[201~C/RELEASE/IFC4x3/HTML/concepts/Object_Association/Material_Association/Material_Constituent_Set/content.html#General-Usage[201~
```

Notice the `[201~` additions and how the pasted content is mangled.

**Comment by tulir** [comment]
Is it up to date?

You should generally paste with ctrl+v instead, but bracketed paste should also work nowadays

**Comment by Moult** [comment]
Ah yes so sorry I updated to the latest and both ctrl-v and shift-ins both work :) Thanks for the help!
