### ISSUE TITLE
Gomuks different behaviour for bare messages across versions

### ISSUE THREAD

**Issue by HexagonWin** [tulir/gomuks#409]
Hello. I had been using Gomuks 0.2.4 on my Devuan GNU/Linux 4 system. 
With bare messages on and channels closed it looks like this:
![gomuks_1](https://user-images.githubusercontent.com/67452729/210673714-e26c5159-ca6b-4f4d-9273-97d7a6b2910f.png)
As you can see the timestamps and nicknames are both visible. As I do not prefer having the nicknames use up space I prefer this kind of view, with the timestamps hidden. But toggling timestamps didn't do anything, so I decided to upgrade to v0.3.0... which had more issues.
![gomuks_2](https://user-images.githubusercontent.com/67452729/210673840-7f04cee7-f8b6-4df1-a42c-b7e09c9152b4.png)
On the exact same settings the user nickname gets hidden when bare messages is toggled, so I'm unable to use gomuks this way.
I'm using the prebuilt linux-amd64 binaries on releases as my computer isn't powerful enough to build gomuks.

**Comment by rihaq** [comment]
Dev is busy.he now works in beeper
