### ISSUE TITLE
gomuks isn't working since last update: blank screen

### ISSUE THREAD

**Issue by martin-braun** [tulir/gomuks#417]
![2023-03-25 1 53 48 AM](https://user-images.githubusercontent.com/24259245/227669795-4d1a144f-aad8-442a-9364-32bfdf19ddce.gif)

macOS 12.6 (21G115)
Installed via Homebrew (latest)

I have no idea how to debug this.

**Comment by DAT4** [comment]
I have same issue on arch from pacman using matrix.org 
I got a login screen but after login success I got this blank screen with an empty thing in the side :)

**Comment by x7upLime** [comment]
This seems related to #150 
It happens to me if I login to a just installed, empty matrix server.. or if I login on matrix.org as a newly created user.

**Comment by martin-braun** [comment]
@x7upLime Not on my case. I was in a session with several rooms and I got this issue after updating the app (I think). Point is, this used to work before.

**Comment by DarienH48** [comment]
I have the same issue in an artix-openrc install and "fixed" it by copying the .cache/gomuks folder from a Void linux install which was working, I can't tell what causes it.

**Comment by oga-sven** [comment]
Hi. Do you have any update? I have the same issue
<img width="949" alt="Screenshot 2024-04-27 at 13 07 06" src="https://github.com/tulir/gomuks/assets/31472764/80f336fe-5120-4ad6-a161-e481e02a1c50">
