### ISSUE TITLE
gitter.im: failed to check server versions

### ISSUE THREAD

**Issue by massigrillo** [tulir/gomuks#419]
Hi, 
I am having issues connecting to gitter
![image](https://user-images.githubusercontent.com/1167131/230191462-b81199ec-1007-46da-b173-caacd5e8c93a.png)

**Comment by tulir** [comment]
That's not the correct homeserver address. It should auto-fill the right address if you type in the user ID (`@user:gitter.im`) while the homeserver field is blank.

**Comment by Damaj301damaj-lol** [comment]
> That's not the correct homeserver address. It should auto-fill the right address if you type in the user ID (`@user:gitter.im`) while the homeserver field is blank.


For some damn reason, the gitter homeserver is **not** gitter.im, its gitter.ems.host
