### ISSUE TITLE
`/toggle newline` doesn't change the functionality of `enter` or `alt`+`enter`

### ISSUE THREAD

**Issue by xplreitr** [tulir/gomuks#434]
`/toggle newline` doesn't change the functionality of `enter` or `alt`+`enter`

Whether or not 'newline' is toggled `enter` continues to submit a message and `alt` + `enter` continues to add a new line. 

I was able to replicate this across 
* a Ubuntu Linux x64 using precompiled binaries, 
* a raspberry pi (amd) using precompiled binaries, and 
* windows using precompiled binaries

**Comment by vn971** [comment]
Confirming on ArchLinux, gomuks version 0.3.0
