### ISSUE TITLE
[Feature request] Configure notifications per room

### ISSUE THREAD

**Issue by cizra** [tulir/gomuks#438]
I don't want to get notifications from some rooms - I'm lurking there and mostly ignoring them, sometimes I ask a question there.

A possible exception would be if someone mentions me by name, or (like Element allows) set keywords to watch for.

Would it be possible to have some sort of roomId -> notificationSettings mapping, in addition to default notificationSettings, where I could override notifications for specific rooms?

**Comment by fhmbrg** [comment]
I totally agree. It would be very comfortable to be able to configure/toggle notifications on a per room basis; except mentions.

Some of the rooms I am in are way too exhaustive to become notified.

**Comment by nteodosio** [comment]
For me the ideal case is: Notification only if mentioned or if received a reply to a thread in which I participated.

To be honest I find popups, the paradigm that these notification daemons adopt, intrusive. Matterhorn has a clever approach[1], that gives the user full power about what to do with a message reply by passing the message and its metadata to a user defined script. Then the user can implement all his whims, alleviating the main program from the burden of implementing and maintaining multiple possible notification preferences.

[1] https://github.com/matterhorn-chat/matterhorn/blob/master/docs/notification-scripts.md
