### ISSUE TITLE
Unable to start v0.3.0 on Windows

### ISSUE THREAD

**Issue by staticfrost** [tulir/gomuks#439]
Unable to start v0.3.0 on Windows
When I start the application get an error: The code execution cannot proceed beacuse libstdc++-6.dll was not found. Reinstalling the program may fix this problem.

**Comment by Bullgoose12** [comment]
I'm getting the same error

**Comment by davidbe** [comment]
I had the same error. I installed gomuks through Scoop, and also neovim. In the /bin -directory of neovim , I found all the necessary files. I copied them to the gomuks-directory. Files needed are:

- libstdc++-6.dll
- libgcc_s_seh-1.dll
- libwinpthread-1.dll
