### ISSUE TITLE
[feature] readline-like input controls

### ISSUE THREAD

**Issue by jficz** [tulir/gomuks#447]
I miss "advanced" input controls I'm used to from shell, like CTRL-W to delete the words, CTRL-K to delete chars to EOL,  CTRL-U to delete whole input, CTRL-ARROW to move cursor by word, etc. These, as I understand, are provided by the GNU readline library and are essentially Emacs bindings. Maybe it can be used for input handling in Gomuks?

Or something similar? Or possibly even vim-like bindings? Or any kind of bindings, really :)

**Comment by peter-** [comment]
Duplicate of #69
