### ISSUE TITLE
Room list bugs can crash the application in some cases

### ISSUE THREAD

**Issue by Cadair** [tulir/gomuks#45]
hey, this is an awesome client. I have had a couple of crashes when trying to send a message in one room. Reports attached.
[gomuks-panic-2018-05-09--15-40-00.txt](https://github.com/tulir/gomuks/files/1988240/gomuks-panic-2018-05-09--15-40-00.txt)
[gomuks-panic-2018-05-09--15-39-50.txt](https://github.com/tulir/gomuks/files/1988241/gomuks-panic-2018-05-09--15-39-50.txt)

let me know if you need more info.

**Comment by tilpner** [comment]
I have another one: 
[gomuks-panic-2018-05-14--19-38-36.txt](https://github.com/tulir/gomuks/files/2001933/gomuks-panic-2018-05-14--19-38-36.txt)
