### ISSUE TITLE
olm security issues path forward

### ISSUE THREAD

**Issue by heywoodlh** [tulir/gomuks#463]
As I am sure most tech-savvy Matrix users are aware, some security issues were recently disclosed regarding OLM: https://soatok.blog/2024/08/14/security-issues-in-matrixs-olm-library/

My understanding is that the Matrix team's official position is to stop using libolm in favor of vodozemac (and per the above linked issues): https://gitlab.matrix.org/matrix-org/olm/-/commit/6d4b5b07887821a95b144091c8497d09d377f985

As an extremely satisfied Gomuks user, I'm wondering if there's any path forward for switching to vodozemac over olm? I'd be disappointed to have to use Element exclusively for a less-vulnerable experience.

**Comment by tulir** [comment]
See https://github.com/mautrix/go/issues/262

**Comment by heywoodlh** [comment]
Thanks, it was difficult to find anything relevant about this, I appreciate the pointer.
