### ISSUE TITLE
/cs fetch  command fails

### ISSUE THREAD

**Issue by mikebakke** [tulir/gomuks#466]
Whenever I try to verify with /cs fetch I get the following error message: Error fetching cross-signing keys: illegal base64 data at input byte 40

This is the static linked amd-64 image running on Debian 12

Trying via web-app by comparing text appears as if it's worked, but the session still shows as unverified.

I can manually export/import/clearcache/restart but that is a little cumbersome and as far as I can see, the session is still actually unverified.

Any thoughts?

**Comment by uriel1998** [comment]
Same issue here; oddly, I've gotten it to verify with a different account; I wanted to have a separate one alongside (used GOMUKS_ROOT environment variable, that part worked great).

**Comment by JRGonz** [comment]
I saw that tulir said in a matrix channel that this is an issue with something that's baked in and they'd try to take a look at it after they worked more on webmuks. I wound up having the same issue as well. is it possible to grab an ancient version of gomuks, verify, then upgrade? I think I may try that later today.

**Comment by JRGonz** [comment]
I guess not. v2 won't even login. v3 just uses the same config / method. The best course of action is to be patient and see if a fix comes out.
