### ISSUE TITLE
Option to change timezone

### ISSUE THREAD

**Issue by turt2live** [tulir/gomuks#47]
despite the fun everything being in UTC because the box I installed it on is UTC

**Comment by tulir** [comment]
Apparently the `TZ` environment variable is already supported. I'm not sure if an additional gomuks-specific option is worth it.

**Comment by turt2live** [comment]
The `TZ` option is good enough for me. Might be worth documenting it, but it's not a critical thing. Closing as fixed, feel free to re-open :)
