### ISSUE TITLE
Better support for finding unread: filter room list, jump to next unread, move unread to the top

### ISSUE THREAD

**Issue by ajkessel** [tulir/gomuks#473]
#194 requests that rooms with unread messages go to the top. I'd like to supplement that request with two other features that would make it easier to find unread messages:

- Option to filter the room list to only those with unread messages
- Keyboard and/or GUI shortcut to jump to the next room with an unread message

**Comment by tulir** [comment]
I think for now (until it's merged to main) I won't use github for gomuks web issues, so for feature requests just send them to the room and I'll add them to https://wekan.mau.dev/b/bNA3peJjgzGEXAYMD/gomuks
