### ISSUE TITLE
End-to-end encryption

### ISSUE THREAD

**Issue by tulir** [tulir/gomuks#55]

**Comment by tulir** [comment]
https://gitlab.gnome.org/World/metaolm looks very interesting. It's planned to be functional by end of March and it could probably be integrated using C bindings or just stdin/stdout.

**Comment by hook-s3c** [comment]
+1

**Comment by ReK2Fernandez** [comment]
Any news on this? thanks <3

**Comment by agherzan** [comment]
Interested in this too.

**Comment by ReK2Fernandez** [comment]
hello... news?

**Comment by tulir** [comment]
metaolm or some new Go megolm library needs to become more usable still for built-in e2ee, but https://github.com/matrix-org/pantalaimon should already be usable.

**Comment by ReK2Fernandez** [comment]
@tulir we do not want to use a third program to run one client... whats the point? we want a build in matrix client that can do e2ee if not is not usable since e2ee is the single most importan feature for most people on matrix, if not we just use IRC/xmpp

**Comment by georgkrause** [comment]
Are there any news on this?
