### ISSUE TITLE
go get -v -u maunium.net/go/gomuks returns 404

### ISSUE THREAD

**Issue by stephenmkbrady** [tulir/gomuks#57]
I get 404's using go get.
$ go version
go version go1.10.2 linux/amd64
Majaro linux
I'm following installation instructions. I'm not using unusual net configuration, no vpn turned on. Am I missing something? I've limited knowledge of go.

`
Fetching https://maunium.net/go/gomuks/ui/messages/parser?go-get=1
Parsing meta tags from https://maunium.net/go/gomuks/ui/messages/parser?go-get=1 (status code 200)
get "maunium.net/go/gomuks/ui/messages/parser": found meta tag get.metaImport{Prefix:"maunium.net/go/gomuks", VCS:"git", RepoRoot:"https://github.com/tulir/gomuks.git"} at https://maunium.net/go/gomuks/ui/messages/parser?go-get=1
get "maunium.net/go/gomuks/ui/messages/parser": verifying non-authoritative meta tag
Fetching https://maunium.net/go/gomuks/vendor/golang.org/x/net/html?go-get=1
Parsing meta tags from https://maunium.net/go/gomuks/vendor/golang.org/x/net/html?go-get=1 (status code 404)
Fetching https://maunium.net/go/gomuks/vendor/golang.org/x/net/html/atom?go-get=1
Parsing meta tags from https://maunium.net/go/gomuks/vendor/golang.org/x/net/html/atom?go-get=1 (status code 404)
`

**Comment by tulir** [comment]
Looks like it just checks all packages in case they are custom import paths. Is something actually broken? I tested with a fresh `$GOPATH` and it did print those, but also worked fine.

**Comment by stephenmkbrady** [comment]
Yes, that helped, thanks. I'm new to Go, I didn't know I needed `$GOPATH` explicity set. It looked like it didn't install with the 404's, setting `$GOROOT` and adding it to `$PATH` also finds it without `$GOPATH`.  
 I assumed go get was going to be a bit like npm installationwise. I should've run a find for it or read the manual. Thanks again, closing.
