### ISSUE TITLE
Replacing emoji descriptions with their emojis

### ISSUE THREAD

**Issue by jcgruenhage** [tulir/gomuks#61]
Going from `:tada:` to :tada: and things like that.

While we're talking about emojis, since some terminals/fonts don't properly support them, going the other way around would be nice too

**Comment by tulir** [comment]
https://github.com/kyokomi/generateEmojiCodeMap might be useful, it can create a text -> emoji mapping [like this](https://github.com/kyokomi/emoji/blob/master/emoji_codemap.go)

**Comment by jcgruenhage** [comment]
the text mapping looks like it should get the job done

It would (for performance) probably be best to try to find the relevant parts in the messages with a regex and then map them to their emoji counterparts using that map. Having an inverse map for displaying the text representations shouldn't be too hard. Thanks for doing the quick research on it!

**Comment by vn-ki** [comment]
I am looking into this issue currently.

Can we use [kyokomi/emoji](https://github.com/kyokomi/emoji) directly inside gomuks? I believe that would make this issue very easy.

**Comment by tulir** [comment]
The `Sprint` function of that library can be used directly, but a new function is probably needed for the emoji->text conversion (for terminals/fonts that don't support emoji properly).
