### ISSUE TITLE
Bash-esque Shortcuts

### ISSUE THREAD

**Issue by gjabell** [tulir/gomuks#69]
Since this is a command-line app, it would be nice if the message box supported bash-esque shortcuts, such as:

- ctrl+a to go to the start of the message
- ctrl+e to go to the end of the message
- ctrl+c to clear the current message (this one might be debatable, but I was always disappointed that this wasn't in weechat)
- others? (can't think of any at the moment)

**Comment by ptman** [comment]
s/bash/readline/ ? .inputrc support?-) https://github.com/chzyer/readline

**Comment by Soundtoxin** [comment]
>     * ctrl+c to clear the current message (this one might be debatable, but I was always disappointed that this wasn't in weechat)
That would be ctrl-u, and ctrl-y to paste it again, going with standard binds again.
>     * others? (can't think of any at the moment)
C-b, C-f, C-n, C-p for back, forward, next, previous, aka alternative to arrow keys. Meta versions of back and forward to move by whole words.
