### ISSUE TITLE
Opening links with mouse does not work

### ISSUE THREAD

**Issue by vranki** [tulir/gomuks#71]
I'm running gomuks in gnome-terminal.

Hovering mouse over a URL underlines it (terminal detects a link) but right clicking it does not open the context menu that normally would open. Also left clicking does nothing.

Workarounds:

Clicking link with ctrl held works.
Switching to plain text mode with alt-l and then clicking link works.

Note: This is probably a problem with terminal and/or the mouse library used. But anyway this is an issue and will cause more bug reports.

**Comment by serussell** [comment]
Can you post more about your set-up?  It's working for me.

**Comment by vranki** [comment]
Ubuntu 18.04, gnome-terminal. gomuks installed with go get.

**Comment by depate** [comment]
Please consider your terminal settings. 

I was fooled by my xfce4-terminal. Which displays clickable links while hovering over it, but needs to hold 'ctrl'-key while clicking.

**Comment by vranki** [comment]
Default settings on default gnome-terminal. Links in any other apps (not using mouse) work as expected. I bet the cause is in the used mouse library, but I have no clue if it's technically possible to fix this issue.

**Comment by wvffle** [comment]
You can click links in most terminal emulators while holding <kbd>Shift</kbd>. This is a workaround for a while now.
