### ISSUE TITLE
go panic 

### ISSUE THREAD

**Issue by depate** [tulir/gomuks#72]
Hey,

I can't say much how the error occurred. Sorry.
Windows was on another virtual desktop and after I switched to it, it crashed.

[gomuks-panic-2018-10-11--18-17-33.txt](https://github.com/tulir/gomuks/files/2469765/gomuks-panic-2018-10-11--18-17-33.txt)

**Comment by tulir** [comment]
Looks like something in the input field code, which has been completely replaced.
