### ISSUE TITLE
Cannot switch rooms with Ctrl+Arrow

### ISSUE THREAD

**Issue by matthiasbeyer** [tulir/gomuks#76]
I'm not sure what causes this, but I cannot switch rooms with CTRL+Arrow. It simply scrolls a line, but not switches rooms.

**Comment by alarmschaben** [comment]
I had the same issue, turns out that I had gomuks running inside a tmux session which intercepted the keypresses. Perhaps that's a solution for your problem, too.

**Comment by matthiasbeyer** [comment]
AFAICR I was not running gomuks in tmux.

**Comment by Midek** [comment]
I noticed room switching with ctrl (or alt) + arrows does not work in urxvt, are you using urxvt by any chance?
Changing view.SwitchRoom to alt+j for example works, so its most likely something about arrow keys in urxvt.

**Comment by erdnaxeli** [comment]
Urxvt here, ctrl + arrow does not work, it print Oa or Ob in the message input, but alt + arrow works.

**Comment by Cyrix126** [comment]
I have the same problem in tmux and in framebuffer. Crtl or Alt does not work and has the same effect as if I was only pressing arrow.
And the menu for switching rooms  (Ctrl+K)  is empty, even if there are rooms at the left.
