### ISSUE TITLE
rooms not getting marked as read

### ISSUE THREAD

**Issue by tidux** [tulir/gomuks#78]
From the screenshot on the README page, it looks like rooms are supposed to drop the bold color when caught up, but I don't see a way to forcibly mark a room as read.  Is this not implemented yet?

**Comment by tidux** [comment]
Update: this issue seems to be a bug in the tview library.  Under the Termite terminal (gtk3/vte), when TERM=xterm-termite, gomuks segfaults and crashes.  When TERM=xterm-256color, the above bug is displayed.  When TERM=xterm, it is displayed properly.  I can use a shell alias as a workaround for now but this is still fundamentally a tview bug, which I commented on in https://github.com/rivo/tview/issues/2 .

**Comment by ztychr** [comment]
I am experiencing this on Gnome Terminal 3.38.3 and gomuks 0.2.4. I am not able to circumvent it with TERM=xterm. Any ideas? I assume it is still a tview bug.
