### ISSUE TITLE
Grey out m.notice messages

### ISSUE THREAD

**Issue by NotAFile** [tulir/gomuks#82]
m.notice messages have a special, less visible look in riot. This helps distinguish the talking from the bot spam. This would be useful to have in gomuks too.

**Comment by jrswab** [comment]
Has this been satisfied in base.go? I see the `return tcell.ColorGray` on line 156.

https://github.com/tulir/gomuks/blob/ae3bb9c7a39202ba462b3b8a0a564804a5517cf4/ui/messages/base.go#L155-L156

**Comment by NotAFile** [comment]
Text is still white for me:

![image](https://user-images.githubusercontent.com/5447747/59550340-ccb0fd00-8f69-11e9-80e4-432521e18732.png)

**Comment by tulir** [comment]
I think the base.go thing only affects unformatted messages currently
