### ISSUE TITLE
Allow manual room ordering like irssi and weechat

### ISSUE THREAD

**Issue by Soundtoxin** [tulir/gomuks#83]
I started to discuss it in an unrelated issue, saw there didn't seem to be one dedicated to this, and now I'm making one. I'd love to have my most-used channels in a static order.

**Comment by tulir** [comment]
Tagged rooms (favorites and low priority are default tags) should be manually ordered already.

**Comment by Soundtoxin** [comment]
How do I change the order of things in my favorites? Also I'd ideally like to order people as well. Probably just alphabetically, but being able to do it manually would probably be a more flexible option.
