### ISSUE TITLE
Alignment breaks with unicode usernames

### ISSUE THREAD

**Issue by jeffcasavant** [tulir/gomuks#84]
My brother, jerk that he is, has set his username on my homeserver to:

⅟0⌚

As far as I can tell the watch emoji is throwing off alignment in the row it's in.

![screen shot 2019-01-18 at 3 47 19 pm](https://user-images.githubusercontent.com/2212754/51412071-5c2bbe80-1b38-11e9-9efa-59551b2007a1.png)

Note I do have the app running inside tmux in Alacritty, on MacOS.  This is the latest version available prebuilt on Maunium.net (11-01-2019).

**Comment by tulir** [comment]
Does this still happen? I can't reproduce on tilix, alacritty or tmux in alacritty
