### ISSUE TITLE
does it support e2ee yet?

### ISSUE THREAD

**Issue by ReK2Fernandez** [tulir/gomuks#88]
Hello, our community that is heavily CLI users weechat, etc etc are thinking in migrating from irc/otr etc to matrix, but needs to be a client with encryption since we are against clear channel communications in 2019 is suicide. Someone told me about gomuks but I can't see anyplace on there readme about what pieces it supports from the matrix protocol.

Thanks

**Comment by tulir** [comment]
Not yet, see #55
