### ISSUE TITLE
Set Gomuks as XDG matrix:// handler

### ISSUE THREAD

**Issue by Evidlo** [tulir/gomuks#89]
I was figuring out how to set up XDG protocol handlers, so I'll document that here.

`~/.local/share/applications/matrix-handler.desktop`
```
[Desktop Entry]
Type=Application
Name=Matrix Scheme Handler
Exec=gomuks join %u
StartupNotify=false
MimeType=x-scheme-handler/matrix
```

`~/.local/share/applications/mimeapps.list`
```
[Default Applications]
x-scheme-handler/matrix=matrix-handler.desktop
```

And finally
```
$ update-desktop-database ~/.local/share/applications/
```

Gomuks would need some mechanism to send a /join to an already running instance.

**Comment by tulir** [comment]
Blocked on matrix-org/matrix-doc#455

**Comment by tulir** [comment]
matrix-org/matrix-doc#2312 is starting to be ready enough that it can be implemented

**Comment by MayeulC** [comment]
Shouldn't be blocked anymore, and there has been some activity on the browser front recently, so the scheme might become more relevant soon.
