### ISSUE TITLE
Highlight messages only if the nick is really activly mentioned/typed

### ISSUE THREAD

**Issue by kaffeekanne** [tulir/gomuks#96]
All messages with a the nick beeing only a substring of a normal word get highlighted. Expected would be highlighting only if the nick is sourrounded by spaces, brackets and some punctuation characters. Very short nicks are prone to this problem.

Example: if the nick is `mark`, `don't use marker pens on monitors!` is a highlighted message, but should not be, as mark != marker.

**Comment by Evidlo** [comment]
Dup of #58

**Comment by kaffeekanne** [comment]
Did not see it in the list. Are you sure its a dup? I don't mind if this issue gets closed then.

**Comment by Evidlo** [comment]
Not a dup.  I misread.
